### ISSUE TITLE
Non-IFRC users require two admins' validation

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#164] opened 2018-02-05 22:21 UTC
> When a non-IFRC user is registering, the notification to the two IFRC users goes for validation.
However even if only one IFRC user validates the new non-IFRC user request, it will get approved in the database as an active user without the second level of validation from the IFRC.

> As well, the non IFRC user does not get any notification of his account being validated.

@guipizzini It was unclear to me that both admins needed to validate. System only requires one, currently.

**Comment by guipizzini** [comment] 2018-02-06 12:20
@dereklieu can this be made that both level of validation need to occur or too complicated? If not, let's keep as it is for now and we can park this for phase 2.0

**Comment by dereklieu** [comment] 2018-02-06 15:02
While this isn't a huge task, if possible I'd like to preserve phase 1 time for critical items.

**Comment by guipizzini** [comment] 2018-02-06 15:12
makes sense. thanks

**Comment by guipizzini** [comment] 2018-02-06 18:39
Moved this to phase 2.0

**Comment by dereklieu** [comment] 2018-06-28 07:56
Done.

**Comment by ElsaRaunioIFRC** [comment] 2019-04-10 08:52
@szabozoltan69 I am reopening this issue due to the increase of problems related to registering non-IFRC email addresses.

I have been trying to register with two non-IFRC emails: elsa.raunio@gmail.com and eraunio@live.com. In both occassions, I provided myself (elsa.raunio@ifrc.org) and Munu (mununuri.musori@ifrc.org) as references. However, in both cases, I received the validation email myself while Munu received nothing. This was despite me changing the order of the references when trying to register second time (with eraunio@live.com). Both elsa.raunio@gmail.com and eraunio@live.com are currently in the list of "Pending users" on GO.

Based on these observations, it looks like the validation emails are not always making it to the assigned references. Could you investigate the root cause of this issue?

**Comment by szabozoltan69** [comment] 2019-04-10 09:17
@ElsaRaunioIFRC I can confirm that your registration happened as you wrote,
```
select user_id, created_at, admin_contact_1, admin_contact_2, email_verified, admin_1_validated, admin_2_validated from registrations_pending where user_id in (3598, 3599)
;
 user_id |          created_at           |     admin_contact_1      |     admin_contact_2      | email_verified | admin_1_validated | admin_2_validated 
---------+-------------------------------+--------------------------+--------------------------+----------------+-------------------+-------------------
    3598 | 2019-04-10 07:16:30.778072+00 | elsa.raunio@ifrc.org     | mununuri.musori@ifrc.org | t              | f                 | t
    3599 | 2019-04-10 08:01:27.020603+00 | mununuri.musori@ifrc.org | elsa.raunio@ifrc.org     | t              | t                 | f
```
In the automated tests there are steps where we simulate such registration, but the email sending is also just a simulation, so in production it can happen something non-wanted. I shall check it...

**Comment by szabozoltan69** [comment] 2019-04-10 09:19
Maybe there is a (non-wanted) swap in the program for admin1/2 validation? Because in the above data it seems to be as if Munu had validated it ("t" as "true"), and Elsa had not ("f" as "false"). Hmmm...

**Comment by szabozoltan69** [comment] 2019-04-12 10:36
I found the clue to the swapping:
```
            admins = [pending_user.admin_contact_1, pending_user.admin_contact_2]
            for idx, admin in enumerate(admins):
                token = pending_user.admin_token_1 if idx == 1 else pending_user.admin_token_2
```
The index is 0,1 – but the postfix is 1,2. So when we are at idx=1 this is not token_1.

**Comment by dereklieu** [comment] 2019-04-12 13:25
@ElsaRaunioIFRC is this a problem only when @mmusori is set as admin, or is it more prevalent? If you set two other people as admin, do they receive the emails? Has he checked his spam folder?

**Comment by ElsaRaunioIFRC** [comment] 2019-04-12 13:42
@dereklieu Yes, @mmusori found the email in his spam folder.

**Comment by szabozoltan69** [comment] 2019-04-15 10:17
Swapping fixed via https://github.com/IFRCGo/go-api/pull/375, 
https://github.com/IFRCGo/go-api/blob/master/registrations/views.py#L322

**Closed by szabozoltan69** 2019-04-15 10:17 UTC
Labels: Tracked by GO Team
