### ISSUE TITLE
[PROD] Map interactions - bug on Chrome

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1868] opened 2021-03-17 10:09 UTC
## Issue
Some users are reporting a bug that map interactions do not work properly. On the [homepage](https://go.ifrc.org/) and [region](https://go.ifrc.org/regions/0#operations) maps, when clicking on points or countries, the pop-up box only occasionally works. On the [emergencies page](https://go.ifrc.org/emergencies), the pop-up never works when clicking on emergency points.

It seems to only be in Chrome and only for some users (works fine for me). 

## Impact
Being on all maps and likely a common way of navigating to operations and country pages, this is a must fix.

cc @batpad @geohacker @tovari

**Comment by batpad** [comment] 2021-03-19 04:18
@jhenshall I am unable to reproduce this. Best might be to get on a screenshare with someone who can reproduce this consistently and try and see what's going on, and then try and narrow down the issue by browser / OS / screen resolution / whatever might be causing it.

**Comment by batpad** [comment] 2021-03-19 04:19
@karitotp would you be able to test this? Test clicking on the points on the map on the pages mentioned in the ticket and see if you're able to reproduce this issue of popups not showing up?

**Comment by karitotp** [comment] 2021-03-19 14:11
@batpad, I tested all this even in different languages and everything is working good to me.

**Comment by tovari** [comment] 2021-03-23 12:53
Who can help to reproduce this issue? @anamariaescobar , @LukeCaley?
@batpad, can we somehow export some Chrome developer tools data that you could analyse?

**Comment by anamariaescobar** [comment] 2021-03-23 16:18
I reproduced it with @batpad this morning in a call.

@batpad let me know if there is something else I can help with!

**Comment by batpad** [comment] 2021-04-12 11:43
@frozenhelium tagging you here as per call - this is a really strange issue - maybe we can ping @anamariaescobar again and get on a call together to look at it and try and pin down what combination of browser / OS / pointing device this seems to be affecting?

**Comment by batpad** [comment] 2021-05-31 07:53
Speaking to @anamariaescobar this seems to have fixed itself for her - the most likely explanation for this bug was a particular release of Chrome that had a bug, and that seems resolved with a browser update.

Will be great to confirm that this seems fixed for all those that were facing the issue. If you are still facing the issue, please leave a comment with the exact browser version (and if you were facing it but no longer, would also be useful to see browser version).

**Comment by anamariaescobar** [comment] 2021-05-31 08:18
Hi @batpad, I confirm that from my side everything is working as expected, I am using Google Chrome Version 90.0.4430.93

**Comment by jhenshall** [comment] 2021-06-01 08:59
Thanks for update @batpad! I know this also affected @LukeCaley - can you confirm it's fixed for you as well?

**Comment by tovari** [comment] 2021-07-07 14:15
No recent reports about this problem.

**Closed by tovari** 2021-07-07 14:15 UTC
Labels: Must Fix, geo
