### ISSUE TITLE
the IFRC Emergency Appeal document is not pulling into GO automatically

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#466] opened 2018-10-02 08:08 UTC
## Issue (by Guido) 

If you check Nigeria (http://go.ifrc.org/emergencies/3136) no GO the DREF appears, but not the Appeal which is however published on ifrc.org which is our data source for these products (http://www.ifrc.org/appeals).

**Comment by dereklieu** [comment] 2018-10-10 21:41
This is a duplicate of #463. The appeal document is missing from the google sheets where this data is compiled from.

@omniscjencja please do a quick check on existing issues before opening one, to see if there is one that already exists for the one you're opening.

**Closed by dereklieu** 2018-10-10 21:41 UTC
