### ISSUE TITLE
[PROD] Line graphs to show all months/years

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#1398] opened 2020-07-15 13:20 UTC
## Issue
The EA/DREF and emergencies graphs on the home page / regional page / emergencies page show the number of these by month or year. In cases that there have been none on a year or month, instead of showing zeros, the graph just skips this leading to an inaccurate "timeline".

E.g. on the MENA refgional page (https://go.ifrc.org/regions/4#operations) in the graph below, April is missing

![image](https://user-images.githubusercontent.com/52411237/87549197-d0074280-c6ad-11ea-9552-1140260d3931.png)

## Expected behaviour
All months or years should show on the timeline, even when there have been no operations or emergencies on that particular month/year

Sidenote that I suppose will be fixed with the new styling, but flagging for now: the "s" in DREFs should be lowercase
![image](https://user-images.githubusercontent.com/52411237/87549779-83703700-c6ae-11ea-8c8b-cf594b862a9f.png)

**Comment by LukeCaley** [comment] 2020-08-18 19:17
@batpad is this currently seen as in scope for 4.3?  If not, please elaborate the desired way forward and time estimate for future prioritisation

**Comment by batpad** [comment] 2020-08-20 06:17
This landed up being a bit more of a rabbit-hole than I had imagined. We may want to spend a bit of time looking clearly at the data passed through to the charts and how and where aggregation happens. We should definitely fix this bug though. Moving to 4.4., happy to prioritize this.

**Comment by batpad** [comment] 2020-12-10 09:31
@karitotp could you verify this work? There should no longer be any missing months in any of the graphs on the region pages.

**Comment by karitotp** [comment] 2020-12-10 21:21
@batpad, there are still some graphs that are not showing all months. For example in Americas, Europe and Middle East & North Africa
![Screenshot from 2020-12-10 15-18-12](https://user-images.githubusercontent.com/11504548/101824966-fb764800-3afa-11eb-85ae-bc0f865f3c00.png)

**Comment by karitotp** [comment] 2021-01-06 19:20
> The EA/DREF and emergencies graphs on the home page / regional page / emergencies page show the number of these by month or year. In cases that there have been none on a year or month, instead of showing zeros, the graph just skips this leading to an inaccurate "timeline".
E.g. on the MENA refgional page (https://go.ifrc.org/regions/4#operations) in the graph below, April is missing

Not all the months appear in the timeline of the graphs, but none are missing between those that appear.

> Sidenote that I suppose will be fixed with the new styling, but flagging for now: the "s" in DREFs should be lowercase

Now, all the title is in uppercase

**Comment by frozenhelium** [comment] 2021-04-26 11:36
@tovari is this the required behaviour?
![2021-04-26-171648](https://user-images.githubusercontent.com/4931541/116076257-b91d6400-a6b3-11eb-8c11-646d090e09d8.png)

**Comment by tovari** [comment] 2021-04-26 13:39
As agreed on the GO call on 26.04., months without any appeals, DREFs should be presented by 0 values on the graph. Thanks!

**Comment by frozenhelium** [comment] 2021-04-27 07:27
Available for testing [here](https://ifrc-go-fix-timeline-charts.surge.sh/)
![2021-04-27-131157](https://user-images.githubusercontent.com/4931541/116202349-31d6fb80-a75a-11eb-94b2-675d926b7033.png)

**Comment by karitotp** [comment] 2021-04-27 13:45
I am seeing that in the graphs one month is appearing twice and one is missing.

![Selection_006](https://user-images.githubusercontent.com/11504548/116249296-48695c80-a732-11eb-9aee-f5ed89b23d9b.png)

https://ifrc-go-fix-timeline-charts.surge.sh/regions/3
![Selection_008](https://user-images.githubusercontent.com/11504548/116250279-32a86700-a733-11eb-8b4e-35f5792b525d.png)

**Comment by frozenhelium** [comment] 2021-04-27 15:12
@karitotp is there any special condition that leads to this behaviour? I'm currently unable to reproduce this
![2021-04-27-205554](https://user-images.githubusercontent.com/4931541/116265764-1c35f600-a79b-11eb-9eb4-f9b9e25ab4cf.png)

**Comment by karitotp** [comment] 2021-04-27 15:39
:thinking: @frozenhelium I think there is not any special condition. I am only testing in Chrome.

I reduce the page size and now it is displaying as :point_down: but the problems with  months is still there.

![Screenshot from 2021-04-27 10-35-03](https://user-images.githubusercontent.com/11504548/116270073-6475f980-a744-11eb-9a99-00d4fa69af6a.png)

**Comment by tovari** [comment] 2021-05-04 09:45
Time period is correctly displayed now. Thanks!
Interestingly, chart format is different at Asia Pacific region. I will create a new ticket to standardize the look of all of them.

**Closed by tovari** 2021-05-04 09:45 UTC
Labels: DFS, Hours, Maintenance
