### ISSUE TITLE
Epidemic figures restructure/rework

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-frontend#1161] opened 2020-04-27 17:16 UTC
Quote https://github.com/IFRCGo/go-frontend/issues/1097#issuecomment-620000648:
> Feedback from Health:
> 
> EPI Key Figures on Emergency pages
> 
> Remove old “Key Figures” for Epidemic Emergency pages: Numbers for “Affected”, “Injured”, “Dead”, “Missing”, and “Displaced” should not show on an Epidemic Emergency page, the same way that the numbers are no longer collected in the Epidemic Field Report. In its place should be the “Epidemic Figures” (see screenshot below). No comment on non-EPI key figures (e.g. “Assisted”, etc).
> ![image](https://user-images.githubusercontent.com/30079559/80399516-9ba79580-88b9-11ea-9138-9766d04d156f.png)
> 
> Epidemic Key Figure Source in header: There should not be multiple sources for Epidemic key figures (see logic above), but rather one source. This one source can be cited, in parentheses following the Header text (e.g. Epidemic Figures (WHO) – screenshot above) or within the italicized “source” text below the key figures (e.g. Source: WHO, 4-27-2020).
> “Confirmed”, “probable”, and “suspect” as sub-classification of “cases”: As in the form design, indent “Confirmed cases”, “probable cases” and “Suspect cases” to visually show that they are a sub-classification of all “Cases”
> Source timestamp: I do not understand why there is a timestamp affiliated with “Source”. “Date of Data” is a DD/MM/YYYY value field with no affiliated timestamp. I am currently concerned that it is pulling Field Report submission timestamp for “Date” rather than the manual “Date of Data” value field. Do not want to show timestamp.

## Restructure of figures
Right now we store data separately (even on DB level) for each source like:
- Probable Cases (WHO)
- Probable Cases (Ministry of Health)
- ...etc

### Route 1
We merge the current 3 fields (WHO, MoH, Other) for each value into 1 field since there will ever be only 1 data for every one of them, and add a new field for `epi_data_source` or something, which would be either a `dropdown` or `radio buttons` with those 3 sources listed.
Then we would just adjust the API and the frontend to use the new fields for those.

Mockup from Roxanne for the possible look of 'Create Field Report' page:
![image](https://user-images.githubusercontent.com/30079559/80400166-b4fd1180-88ba-11ea-8842-61426e6ccf04.png)

Possible **issue** with this route is that if we want to have separate sources in the future we have to redo all that we have now.
We would **gain** cleaner code and some easier logic to maintain.

### Route 2
We keep the current data structure explained in _Route 1_ but adjust the code to only show and use the relevant data, and adjust the 'Create Field Report' page only to restrict the use of source field-by-field.

Possible **issue** with this is that we will have some spaghetti code (harder to maintain) both on backend/frontend.
We would **gain** the ability to adjust quicker if the requirements change later to handle the figures differently if they come from different sources. _This doesn't mean we couldn't easily handle them with Route 1 if they still had only 1 source per Emergency/Field Report_

## Cases
`suspected`, `probable`, `confirmed` cases to be summed into the plain `cases` field and make `cases` non-editable. This should be pretty straightforward to do on the frontend and not even saving the value so it only ever shows a calculated value everywhere. Need to adjust logic wherever it's used.

cc @batpad @mmusori @nanometrenat

**Comment by mmusori** [comment] 2020-04-29 11:59
We will take route 1 which is inline with the suggestion from health.

**Comment by GregoryHorvath** [comment] 2020-04-29 12:06
@yellowumbrella-design asking for some guidance on the (future) implementation of the frontend parts for this.

In short, we will only have 1 field for each "cases, dead" fields instead of having separate for WHO, MoH, Other, and only 1 source selectable for all the figures. Thus why it would be needed to adjust:
- Field Report page's EPI figures design
![image](https://user-images.githubusercontent.com/30079559/80593932-5b175b80-8a22-11ea-8ea1-f73b8b0b2a01.png)
- Create Field Report page's design somehow as shown in an above screenshot
- EPI figures shown on the Emergency page as shown in an above screenshot

**Comment by yellowumbrella-design** [comment] 2020-04-29 12:50
@GregoryHorvath Is this the field report page or the emergency page? We have some wireframes for both. Can you please take a look? I think they may have already addressed that:
https://invis.io/49WZCQ0QVTY#/412009430_4-4-3_GO_FieldReport-Epi_Page - Field Report page
https://invis.io/59WZFUYEFTM#/412675366_4-2-1_GO_Specific-Emergency_Epi - Emergency page

**Comment by mmusori** [comment] 2020-04-29 13:25
These wireframes work. The only consideration is that the "Source" for Cases, probable cases, suspected cases & confirmed cases will be be the same. "Dead" can have a different source.

**Comment by yellowumbrella-design** [comment] 2020-04-29 13:54
@mmusori Should we then adjust the field report forms as well? Since currently we allow them to add a source individually for each of those.

**Comment by mmusori** [comment] 2020-04-29 13:57
Yes the form needs to be adjusted so that they only put in one source for Cases (Probable, suspected, Confirmed) and Dead. Dead also should have the same source. So before or after they have put in all the figures they can choose the source.

**Comment by GregoryHorvath** [comment] 2020-04-30 08:07
Quick note I forgot: plain `Cases` to be editable still but if any other `X Cases` is edited, re-sum them into `Cases`.

cc @yellowumbrella-design @mmusori

**Comment by batpad** [comment] 2020-04-30 08:33
> Quick note I forgot: plain Cases to be editable still but if any other X Cases is edited, re-sum them into Cases.

This logic makes me really uncomfortable. At the very least, then, re-summing should be performed with explicit user action? Being able to edit Cases, but then editing something else and it changing automatically seems a bit strange as a user, and also really tricky to manage in logic.

**Comment by GregoryHorvath** [comment] 2020-04-30 08:39
> > Quick note I forgot: plain Cases to be editable still but if any other X Cases is edited, re-sum them into Cases.
> 
> This logic makes me really uncomfortable. At the very least, then, re-summing should be performed with explicit user action? Being able to edit Cases, but then editing something else and it changing automatically seems a bit strange as a user, and also really tricky to manage in logic.

Wondered if it should work like the other idea of having the Field Report's `title` constructed from 3-4 other fields or somthing but since this is a last step most probably for the implementation so it's an open discussion for sure.

**Comment by GregoryHorvath** [comment] 2020-05-05 12:25
In a call with @batpad we agreed on the need of reworking the data structure for multiple purposes, and he made some good comments on how to properly quality check the changes even before deploying them to staging.

The main concern was how do we roll the current **source** of the figures into the new field:
- there will be a script listing all Epidemic Field Reports which have multiple sources set for their figures
- there will be a script determining if all the current sources for each figure of a Field Report are the same, then we just copy that
- clarifying with @mmusori if a Field Report has multiple sources of figures we set it to the "plain" **cases**' one
- we will only make the previous fields read-only on the backend and hide from the frontend, and not remove anything until the next release/we're sure everything works well with the new data structure

**Comment by batpad** [comment] 2020-05-05 14:07
> clarifying with @mmusori if a Field Report has multiple sources of figures we set it to the "plain" cases' one

@GregoryHorvath could you clarify this further? My understanding is that for the EPI field reports, you will be required to have a single source for all the data? Are you saying that if there's multiple sources in the current data, we will just omit the source data during the migration and set the source to Null?

**Comment by GregoryHorvath** [comment] 2020-05-05 14:34
@batpad So Munu told me there should be 0 EPI Field Reports with multiple sources but if we find any, we should just set the source of those to the one set for `..._cases`

Though I'd suggest we do the deployment of this (if it's ready) with Munu present and if there are any problematic cases we could act on the fly there.

**Comment by batpad** [comment] 2020-05-06 05:43
> @batpad So Munu told me there should be 0 EPI Field Reports with multiple sources but if we find any, we should just set the source of those to the one set for ..._cases

@GregoryHorvath I would strongly recommend not getting into a case where we have EPI field reports with a `null` value for source, since that might really mess-up the logic in other places. It's great that it seems like existing reports which may have values from multiple sources should be a number close to zero. Then let's just fix them while importing, yes. As discussed, let's maybe have one script to just log / output cases where there are multiple sources, so we can assess?

But, apart from handling this edge case of existing reports where there maybe multiple sources of data, everything you've got looks fantastic to me. Let this not be a blocker for moving ahead, for sure. Looking forward to reviewing code when it's ready.

**Comment by nanometrenat** [comment] 2020-05-10 18:52
Just a quick note - if any fields are being deprecated as part of this work (i.e. db fields that will never contain any data) may these fields also please be removed from the field_report API ?
currently there are fields being returned that I don't think have any way of currently being populated as they are nothing to do with the epi "sources" e.g.  "who_num_assisted" and "health_min_num_assisted"
Thanks

**Comment by nanometrenat** [comment] 2020-05-10 21:18
Actually @GregoryHorvath @mmusori @batpad @LukeCaley the above (making sure that we don't have extraneous "figures" fields coming through in the API) is more urgent than I had thought at first glance.  Not only are there 75 fields per Field Report now (of which the vast majority are "figures" fields - but ALL of these also come through in the Event API, for every Field Report for an Emergency.  Given that one NS is now up to 48 Field Reports for their emergency, that means we now have 3574 columns in a csv export of the Event API........!!!  And the columns will increase by 75 each time that NS submits another report.

Think there are two things here:
1) making sure that unnecessary fields don't come through for each Field Report - as per this ticket (rationalising epi figs), and
2) separate discussion to be had as to what from each FR should come through on Event API (separate ticket to be logged)

**Comment by mmusori** [comment] 2020-05-11 08:24
@GregoryHorvath the select source solution is perfect. I have reviewed the Emergency page and the Numerical details with Roxanne and they met requirements. Two things  1. I spoke with Sune and he agrees with the suggestion from Roxxanne that for Covid Field Reports **only** we should remove the probable, suspected and confirmed cases and just have Cases and Dead. 2. We might want to open a separate ticket no hiding fields without data.

**Comment by GregoryHorvath** [comment] 2020-05-11 15:25
Confirmed in a call with @mmusori that for older Field Reports we convert the `affected` into `cases` and if the source is `gov` we use `health`, if the source is `ns` we use `other` as the `epi_figures_source`.

cc @batpad

**Comment by mmusori** [comment] 2020-05-13 09:06
After our call today with @GregoryHorvath we have agreed on the following for the upcoming deployment.
1. Remove Info bulletin from Covid 19 field report and associated flows. 
2. Switch the title and select existing  Emergency for all FR
3. On the actions,  replace "Movement " with partner for the field "Number of RCRC Movement personnel" for FR. But for Covid FR remove the field completely.
4. Hide all blank Numeric fields including their title for FR output page and Emergency Page and Notification. Need to review how this affect the page.

**Comment by GregoryHorvath** [comment] 2020-05-13 17:04
@mmusori Had a quick call with @nanometrenat about what should we really do with all the previous data because I ran into some problems with the above mentioned logic in my comment.

We agreed on:
- only need to copy the data from the `health_min...` `who...` `other...` fields to the new `epi...` cases ones from 15th of April ~17:00 Geneva time since before we didn't even have the current cases fields on production
- figured out we can only see the older `...affected` `...injured`, etc fields for Early Warning Emergencies if their type was Epidemic, but if it was the plain Event type then it showed the `...cases` fields with 0 data
  - couldn't find any Emergency having data in both the `...cases` and `...affected` fields so that could be one option to decide which fields we're showing or...
  - we simply show the `...affected`, etc fields for Emergencies made before 15th of April regardless of the type (this needs some experimentation)

cc @batpad

**Comment by GregoryHorvath** [comment] 2020-05-14 07:58
As agreed with @mmusori on Teams the
> 4. Hide all blank Numeric fields including their title for FR output page and Emergency Page and Notification. Need to review how this affect the page.

is bigger work than estimated, we can leave it out for the next deployment and made it a separate ticket so we'll be able to close this after.

**Comment by GregoryHorvath** [comment] 2020-05-14 13:11
Deployed to staging.

@mmusori @teklal @LukeCaley @nanometrenat

**Comment by mmusori** [comment] 2020-05-15 10:30
Issue 1102 resloved with this ticket: 

![image](https://user-images.githubusercontent.com/7780809/82041034-cfe7c800-96a7-11ea-98e5-f3e39d6076bf.png)

**Comment by mmusori** [comment] 2020-05-18 15:52
1.	Emergency page meets requirements
•	Covid style figures pulling in (Cases and Dead)
•	Epi figures pulling through (Cases , indented (Probable, suspected, confirmed)
•	Single source pulling through
•	Source changes when field report is updated
•	RCRC personnel removed from Covid Input page
•	No Date of data  timestamp
2.	Field Report input template
•	Template has only Cases and dead for Covid. For Epi it has Suspected Probable and confirmed indented to show hierarchy 
•	Template has data of data and source of data. Source is a select one dropdown.
•	**Date of data not yet following prescribed logic ticket 1112 for Phase 4.3.** 
•	**Toggle button for selecting Covid related not yet changed to radio button.**
•	Info Bulletin tab removed
•	Title and Select Emergency switched. 
•	RCRC personnel removed from Covid Input page. Text changed for Epi field report and event/EW field Reports. 
•	Switching of places between Socioeconomic and NS pillars done.
3.	FR Output page and Emergency Page. 
•	**Hiding all blank Numeric fields including their title for FR output page and Emergency Page and Notification. This is now part of 4.3 . Ticket 1231**

4.	Previously created Emergency Pages.
•	Editing an Epi Field report with the toggle button set to Covid Related changes the layout of the Emergency page and the Output FR. It will only have Cases and Dead and will not have Delegates. 
•	Submitting a Covid Field report where there is an Epi style Emergency page changes the layout of the Emergency page and the Output FR. It will only have Cases and Dead and will not have Delegates. Both FR will be attached.

**Comment by karitotp** [comment] 2020-05-18 23:39
The above descriptions are in the site.
In case of the report input template, the button for selecting a Covid related report is already a radio button.

**Comment by nanometrenat** [comment] 2020-05-19 19:13
Moving to Done as this was released to Prod this morning - @mmusori to close when happy!

**Closed** 2020-05-20 11:02 UTC
Labels: feature
