### ISSUE TITLE
[Dev] Emergencies page payload is null

### ISSUE THREAD

**Issue by GergiH** [IFRCGo/go-frontend#1561] opened 2020-09-09 08:48 UTC
## Issue
Hovering over the empty "EMERGENCIES OVER THE LAST YEAR" box gives the following error
![image](https://user-images.githubusercontent.com/30079559/92576319-b0456280-f289-11ea-9b50-481e1d235f02.png)
```
The above error occurred in the <Tooltip> component:
    in Tooltip (at emergencies-dash.js:80)
```

## URL
https://dsgoproxyapp.azurewebsites.net/emergencies/

## Steps to reproduce
- go to the above URL
- hover over the "EMERGENCIES OVER THE LAST YEAR" box
![image](https://user-images.githubusercontent.com/30079559/92577218-b5ef7800-f28a-11ea-96ea-2d030c853a9c.png)

## Expected behaviour
Error should not occur...

## Criticality/Urgency
~Release blocker.~ Currently, this can only be a minor dev-annoyance factor

**Comment by GregoryHorvath** [comment] 2020-09-09 09:17
This seems to happening because when I switched to use the staging API instead of my local one it didn't log me out from the frontend but the API was giving `401 - Unauthorized` responses probably because of my local user was logged in still.

This way it's not really a blocker anymore and it's rather unlikely that we'll have no data in that box for this error to occur again (or unless we switch APIs with totally different Users in it for production).

**Comment by batpad** [comment] 2020-09-09 09:24
@GregoryHorvath thanks for reporting and the follow up.

Yes, I have noticed errors when moving my local development env from local to staging and vice-versa and not clearing browser cookies. This is a very specific case in the developer environment, and I would be in favour of closing this.

**Comment by GregoryHorvath** [comment] 2020-09-09 09:29
> @GregoryHorvath thanks for reporting and the follow up.
> 
> Yes, I have noticed errors when moving my local development env from local to staging and vice-versa and not clearing browser cookies. This is a very specific case in the developer environment, and I would be in favour of closing this.

I thought about closing it too because of the original use-case. I just don't know if we'd want to fix the error caused by the `<Tooltip>` if this has no data as shown on the screenshots, so thus I kept it open.

**Closed** 2023-02-16 14:57 UTC
