### ISSUE TITLE
cannot delete relevant documents and cannot even upload documents

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#465] opened 2018-10-02 08:02 UTC
## Issue (by Guido and Elsa) 

Two issues very critical to the system and our operations.
 
1.      I still cannot delete relevant documents;
2.      And now we cannot even upload documents.
 
Elsa and myself have been trying to upload PDF maps on the Nigeria Floods page and we get an error redirect message and cannot upload PDFs to the relevant section.
 
We’ve tried on different machines, on different networks and browsers.

**Comment by dereklieu** [comment] 2018-10-10 21:32
On deleting, see my note about #464 

On uploading, it appears only documents above a certain size fail. This is a duplicate of #206

**Closed by dereklieu** 2018-10-10 21:32 UTC
