### ISSUE TITLE
'Edit event' button redirect

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#791] opened 2019-09-02 13:41 UTC
## Issue

Edit event button on the emergency page (e.g. https://go.ifrc.org/emergencies/3751#details) redirects to root folder for the back end (https://prddsgocdnapi.azureedge.net/).  This is confusing for users.  

## Expected behavior

Clicking on this button should redirect to the emergency page (e.g. https://prddsgocdnapi.azureedge.net/api/event/3751/change/)

**Comment by batpad** [comment] 2019-09-02 15:33
@LukeCaley that's strange, I can't reproduce. I.e. for me the button takes one to the correct page - i.e. https://prddsgocdnapi.azureedge.net/admin/api/event/3751/change/ .

Maybe a quick screenshare or so will clarify.

**Comment by guipizzini** [comment] 2019-09-06 03:11
<img width="1216" alt="Screenshot 2019-09-06 at 05 10 35" src="https://user-images.githubusercontent.com/23258092/64398330-bf854500-d064-11e9-9126-36e79edb104e.png">
This works properly - screenshot in attachment with url reference of where you will be redirected when clicking edit event. Moving this to done and UAT completed

**Closed** 2019-09-06 03:12 UTC
Labels: UAT approved
