### ISSUE TITLE
[PROD] Field Report Submission Error

### ISSUE THREAD

**Issue by necoline** [IFRCGo/go-frontend#1077] opened 2020-04-03 01:33 UTC
## Issue
We have had two users that have not been able to submit a field report but have gotten "Error: Could not submit field report." I've been trying to figure out where the problem lies but it doesn't seem to be an unsuitable/bad data issue. 
(https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/views/field-report-form/index.js)

and the user checked with the chrome developer tools and got 400 with POST

https://prddsgocdnapi.azureedge.net/api/v2/create_field_report/

## Steps to reproduce
@GregoryHorvath Do you have steps to reproduce this?

**Comment by GregoryHorvath** [comment] 2020-04-03 06:30
@necoline @batpad @geohacker @frozenhelium 

As much as I found is that it's most probably this part when it fails, but couldn't reproduce the issue in any way yet:
https://github.com/IFRCGo/go-api/blob/b66e4565ce8483c0d7d143369568cba9a2eaa0a9/api/drf_views.py#L579-L590

Since the users get the error hardcoded on the frontend my guess would be that somehow the `serializer.is_valid()` fails but the `serializer.errors` is `{} - empty`, which would be really really strange. Though I'll try and throw a `BadRequest` with errors for myself to see if those error messages even came through to the frontend, soon.

The frontend part:
https://github.com/IFRCGo/go-frontend/blob/b55c9d0c33d06f11e57a2392b946f2360dd8715e/app/assets/scripts/views/field-report-form/index.js#L80

**Comment by batpad** [comment] 2020-04-03 06:47
Hey @GregoryHorvath -- I think the ideal steps to follow here would be:

 - Figure out how to make this reproducible. We will need to do this. Even if it's something specific to data on production, we will need this to be reproducible with clear steps to debug clearly.
 - Once we have that, then being able to try and `print` specifically what's failing when saving the field report around the area you pointed to on the backend seems like a good next step.
 - Then, hopefully that's able to give us a better clue whether the problem is with the backend, or the way the frontend is sending some frontend data.

My hunch is that this is some data that is hard-coded on the frontend, like the countries data, that is some-how mismatched with the backend. But it's impossible to tell without getting a reproducible test case, etc.

Longer term, it would definitely be great to remove that broad error catch on the backend and make the error messages more specific, and then of course, have the frontend be able to display better errors to the user.

@GregoryHorvath I should be more available today - please reach out if I can help.

**Comment by GregoryHorvath** [comment] 2020-04-03 06:56
> Figure out how to make this reproducible. We will need to do this. Even if it's something specific to data on production, we will need this to be reproducible with clear steps to debug clearly.

@teklal sent me the data one of the users used, but I was able to create a new FR. Even tried to fiddle around with different combinations like changing/removing the `start date` field, or filling some description fields with thousands of characters and such, but all of those created a FR successfully still.

> Once we have that, then being able to try and print specifically what's failing when saving the field report around the area you pointed to on the backend seems like a good next step.

I was wondering if we should "silent-push" a change (change the current code manually) with printing these into a logfile or console and see if those help, but it sounds a bit more risky to do...

**Comment by batpad** [comment] 2020-04-03 07:09
> I was wondering if we should "silent-push" a change (change the current code manually) with printing these into a logfile or console and see if those help, but it sounds a bit more risky to do...

This is a good last resort idea if we are not managing to find any other way to reproduce. This is really strange though. Should we get details of the browser the user used, to try and reproduce? Though this would be really strange if it were a browser issue.

But if we cannot reproduce, turning on some logs and then inspecting them when this error occurs sounds good to me.

**Comment by GregoryHorvath** [comment] 2020-04-03 07:27
> Should we get details of the browser the user used, to try and reproduce? Though this would be really strange if it were a browser issue.

The user said they checked Chrome devtools and got `400` as a response so that shouldn't be an issue.

**Comment by nanometrenat** [comment] 2020-04-03 07:52
Note past "could not submit field report" issues include
https://github.com/IFRCGo/go-frontend/issues/987 (source selected but no data)
https://github.com/IFRCGo/go-frontend/issues/936 (to do with trying to submit for a territory that is not an IFRC country - e.g. have this issue if submitting Field Reports for New Caledonia rather than France)

**Comment by GregoryHorvath** [comment] 2020-04-03 08:50
@batpad @necoline 
The frontend error object seem to have a `detail` property if there are errors, so I used that for now:
* backend: https://github.com/IFRCGo/go-api/commit/b4594dcea880570af53092f5e766ce24df5d5894
* frontend: https://github.com/IFRCGo/go-frontend/commit/6742c89b443188ddbf849047a9c42b5a4a38afb1

I created the backend branch from `master` just in case but the frontend one is from `develop` so if we'd want to push these into prod asap probably it would mean the frontend one needs to branch out from `master` too.

I'll add the loggin into `.log` files too soon to the backend branch.

**Comment by teklal** [comment] 2020-04-03 14:19
One of the field report submission errors reported to us this past week was due to the same problem as flagged in #987 and the user has now been able to successfully submit a report.

**Comment by teklal** [comment] 2020-04-15 15:38
Adding to the list of known scenarios where this error occurs:
If a user uses a dot (".") in the numeric fields, e.g. as a thousand separator, they get the same error upon submission

**Comment by GregoryHorvath** [comment] 2020-04-15 16:30
> Adding to the list of known scenarios where this error occurs:
> If a user uses a dot (".") in the numeric fields, e.g. as a thousand separator, they get the same error upon submission

Oh nice catch. Thousand separators are a **reeeally** tricky thing to pull off right. I've only found there are some `decimal` fields for the Appeals but other than that most other fields use simple `integer` types. So I think it tried to handle those numbers like if they were decimals instead of handling the `.` as thousand separators.

**Comment by nanometrenat** [comment] 2020-05-21 16:36
@mmusori FYI just had another submission error reported.  Have put this to "triage" for 4.3 as it would be great to get these fixed :)

**Comment by nanometrenat** [comment] 2020-05-22 18:47
Today I replicated a "could not submit Field Report" error whereby the user was trying to EDIT an existing Field Report, to associate it with a different emergency.  The 400 error was returned on PUT https://prddsgocdnapi.azureedge.net/api/v2/update_field_report/12571/ and the message from the back end was
`"content": {            "size": 58,
            "mimeType": "application/json",
            "text": "{\"event\":[\"Invalid pk \\\"4279\\\" - object does not exist.\"]}"
          },
          "redirectURL": "",`
Turns out this was because in the "Please check for an existing emergency" Elasticsearch was returning an emergency that had since been deleted (as part of the "gardening") but the user had no way of knowing that it was a deleted emergency they were linking to as opposed to another emergency of same name.  An ad-hoc re-index meant the user could then search for the existing emergency.  We will need to address this issue under https://github.com/IFRCGo/go-frontend/issues/989 but putting here as it's another reason for a user getting the "could not submit field report" error.

**Comment by batpad** [comment] 2020-05-25 07:19
Moving this to 4.3 as `Needs Spec` because I think we still have errors that we need to figure out the best way to deal with, but we need to spec out exactly our approach, both on the logging and error message side, as well as fixing the root causes of these.

**Comment by nanometrenat** [comment] 2020-06-08 19:39
> Moving this to 4.3 as `Needs Spec` because I think we still have errors that we need to figure out the best way to deal with, but we need to spec out exactly our approach, both on the logging and error message side, as well as fixing the root causes of these.

Thanks @batpad - who do you think needs to be doing the spec-ing?  Be great if we assign in the right direction... thanks a lot!

**Comment by nanometrenat** [comment] 2020-06-25 17:13
Hi @batpad @GregoryHorvath I see this ticket is at Awaiting Spec but that there was a change made in the release.

Can you please confirm if you're thinking that the latest change solves the issue, or if there is further work required under this issue?  FYI it's something we can't test directly in Production (as can't submit FRs) but someone might be able to force errors in Test to verify this untested change - perhaps @karitotp ? THANKS!

cc @LukeCaley @teklal

**Comment by GregoryHorvath** [comment] 2020-06-26 11:33
@nanometrenat The latest changes which were deployed are only fixing the error message, although it 99% of the time happens by some user-input error (last time I heard that the date-picker might not always work in Mac's Safari (?) @teklal). I'd say if we can pinpoint the actual error happening frequently (if any) that we'd make a separate ticket about that, which the correct error message should help with.

**Comment by nanometrenat** [comment] 2020-07-29 13:13
@batpad should this ticket stay open?  thanks a lot

**Comment by LukeCaley** [comment] 2020-08-10 21:06
@batpad grateful if we could take another look at this one to diagnose and split out elements for fixing reported user blockers.

**Comment by batpad** [comment] 2020-08-11 08:40
I've wanted this issue to remain open until we have a fix for #987, which is a known issue which prevents users from submitting field reports and produces weird errors.

We have also overall tightened validation throughout the form, which should now be on staging: https://github.com/IFRCGo/go-frontend/pull/1475

We are quite close to having a fix for #987 : https://github.com/IFRCGo/go-frontend/pull/1513 - once we have this known issue fixed, along-with the better error messaging we have in place now, I think this would be good to close if we don't face any new reports of errors from users.

**Comment by batpad** [comment] 2020-08-20 06:25
We have a fix for #987 in staging, and much tighter validations on the frontend to catch bad data before it gets submitted to the backend. Moving this to `Ready for QA` - I would like to close this and re-open in case we hear of any new Unknown Errors on the field report submission.

**Closed** 2020-09-23 11:51 UTC
