### ISSUE TITLE
Nepal districts don't have any attributes in the shapefile

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1422] opened 2020-07-21 10:07 UTC
In the ICRC admin1 shapefile, some districts in Nepal don't have any attributes.
![image](https://user-images.githubusercontent.com/371666/88041247-bf504400-cb67-11ea-8cb7-0f95b82a1e0b.png)

_the ones in yellow, all attributes are NULL_

We need at least the ADMIN01COD and iso2 so these can be associated correctly.

@batpad @teklal I'm not entirely sure who this should be assigned to as I don't know who has previously edited these shapefiles.

**Comment by geohacker** [comment] 2020-07-23 14:07
cc @guipizzini

**Comment by guipizzini** [comment] 2020-08-03 07:17
As said, it is best to await that our GIS dedicated resource arrives as there is a lot to be done in understanding what has occurred with the Geospatial layers. @LukeCaley would you agree to put this on hold, please? The more we advance on this the more it will be complicated with Johnny to back track what needs to be improved and fixed and for him to set up a streamlined process.

Why am I saying this? Because if we look at our GIS shapefiles, that should be aligned on what is on GO (not the case...) we see that we do have the code elements that the Dev Team is missing on GO...
![ICRC shp](https://user-images.githubusercontent.com/23258092/89155978-9457ee00-d572-11ea-89ee-b1f2f1cc7d6e.png)

**Comment by jhenshall** [comment] 2020-08-27 15:28
New Nepal districts have been added to staging, thank you @geohacker and @GregoryHorvath. Old districts have been kept to avoid breaking field reports that are already linked to them. Will need to add a `deprecated` field to all districts so that those with value `TRUE` can be excluded from dropdown boxes etc.

**Comment by jhenshall** [comment] 2020-10-05 11:32
The new Nepal districts have been added with most of the data added that was missing. They are, however, still missing the admin1 code. This is captured in #1188 so closing this ticket as a duplicate of the remaining work.

**Closed by jhenshall** 2020-10-05 11:32 UTC
Labels: geo
