### ISSUE TITLE
[PROD] Surge Alerts not showing on Emergency pages

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1081] opened 2020-04-05 12:00 UTC
## Issue
Surge Alerts section no longer shows on Emergency page in Production, but should.

## Steps to reproduce
Go to https://go.ifrc.org/emergencies/3972#details or https://go.ifrc.org/emergencies/3925#details - the only sections that show are

- Situational Overview
- Deployed Personnel
- Appeal Documents
- Response Documents
- Contacts

As there have been Surge Alerts for these emergencies, there should also be an Alerts section.

I can see that the Alerts are still linked to these emergencies because when I go to https://go.ifrc.org/alerts/all the alerts show there and I can click through to the relevant emergency pages.

So need to figure out why not showing on the Emergency pages any more.  This seemed to stop working on Friday 3rd at around 2pm GVA time.

## Impact
Impacts everyone looking at the Emergency pages.

## Severity
Deployments still show, just not alerts.

## Is there a workaround?
Users can go to the All Alerts page

**Comment by nanometrenat** [comment] 2020-04-05 12:02
NB same problem in Staging, where Alerts don't show on their respective Emergency page

**Comment by nanometrenat** [comment] 2020-04-07 11:44
Surge alerts now showing the COVID emergency page in Prod as at today:  https://go.ifrc.org/emergencies/3972#details

**Comment by nanometrenat** [comment] 2020-04-07 15:51
As at right now, surge alerts are again NOT showing on the COVID emergency page in Prod:
https://go.ifrc.org/emergencies/3972#details  So we are back to only having the sections listed above showing.
In all these cases I have definitely been logged in.  I cannot see any reason why this is changing back and forth.

**Comment by batpad** [comment] 2020-04-08 14:26
Fix for this has been deployed to testing URL: https://ifrc-go-fix-emergency-surge-alerts.surge.sh

@nanometrenat could I ask you to confirm the fix? If all looks good, will merge this to staging. Thanks.

**Comment by nanometrenat** [comment] 2020-04-09 09:07
@batpad confirmed passed in that testing URL - if I navigate to https://ifrc-go-fix-emergency-surge-alerts.surge.sh/emergencies/3786#details I can see surge alerts, and if I refresh/put the URL in directly I can still see surge alerts.  Many cheers

**Comment by teklal** [comment] 2020-04-09 09:16
Yes, I noticed the same yesterday and mentioned it on this comment https://github.com/IFRCGo/go-frontend/issues/1013#issuecomment-611128719 on the vanity URL ticket.

It seems that the surge alerts and deployments are not fully filtered. At least for the deployments all "active" ones regardless of country and emergency show up on all emergency pages.

**Comment by teklal** [comment] 2020-04-09 09:38
The reason why "Test" and "Afghan" point to the same emergency is that when creating an alert, in the backend instead of taking the name of the event it is linked to as the emergency name to show on the frontend, there for some reason is a field "Operation" that a user can specify (not a dropdown of existing ones etc) and that is the info that shows on the frontend.
![image](https://user-images.githubusercontent.com/52411237/78879565-59c2c680-7a54-11ea-9bde-ce00b252d57f.png)
I was just last night splitting hairs over this same observation and noted it down to be discussed. 
To me the "Operation" field seems redundant and I don't really know what value add it brings, so maybe we could consider eliminating that field altogether. Anyway regardless of that, I think the text that should show on the frontend under emergency should be the name of the "Event" that it is linked to on the backend.

I'll bring this up on the call today and I can create a new ticket for that change if we decide to do something about it. Thanks all!

**Comment by batpad** [comment] 2020-04-09 10:28
@teklal thanks for the detailed explanation here - this whole thing confused the hell outt've me, but then yes, I checked and both pointed to the same Emergency, so it didn't seem like a "bug", but definitely confusing, and I wasn't sure if this was by design.

Yes, please feel free to create a separate ticket with any suggestion to make this less confusing - I have very little context on what the `Operation` text field vs. `Emergency` is used for, etc.

Thanks!

**Comment by nanometrenat** [comment] 2020-05-07 13:56
Think this can be closed - original issue solved (THANK YOU), and as per Tekla comments above if further changes are desired then they can be logged separately.

**Closed** 2020-05-12 08:51 UTC
