### ISSUE TITLE
PER Blocker:  Preparedness tab does not render in Staging site

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#943] opened 2020-01-27 15:22 UTC
## Issue
https://dsgoproxyapp.azurewebsites.net/preparedness does not function.  When it first loads we start to see the correct Preparedness page content for a brief moment, then it is swiftly overwritten by a blank grey screen.  When using dev tools we can see a number of errors and warnings (e.g. Can't perform a React state update on an unmounted component; Failed to load resource: the server responded with a status of 500 (); Uncaught Type error; Invalid prop etc.

## Steps to reproduce
Log in to GO Staging site, click on 'Preparedness' link at top.  https://dsgoproxyapp.azurewebsites.net/preparedness

## Expected behavior
Preparedness page should load with content.

## Related feature
PER #865 

## Criticality/Urgency
This is a blocking issue for PER in test - and PER is our most urgent test item right now.

**Comment by necoline** [comment] 2020-01-27 15:48
this is fixed in #941

**Comment by nanometrenat** [comment] 2020-01-27 15:54
@batpad @frozenhelium there are several pull requests that look like they need to be reviewed and then released to staging.  Can you please do the necessaries ASAP to get these changes into staging so that PER testing can proceed?
Thanks a lot

**Comment by necoline** [comment] 2020-01-27 16:26
I just decoupled this bug fix from the feature changes in the above mentioned PR. The fix is now isolated here: #944 so that it will be easier to review and approve

**Comment by nanometrenat** [comment] 2020-01-28 16:46
Thanks Necoline, closing this ticket as has been fixed in Staging, however new ticket 946 is for a different page but same symptoms.

**Comment by teklal** [comment] 2020-02-04 12:31
This is an issue again. The Preparedness tab does not currently render in the staging environment but gives a blank page.

**Comment by batpad** [comment] 2020-02-04 12:53
Sorry, inadvertently closed.

**Comment by batpad** [comment] 2020-02-04 13:08
@necoline - this seems to be reproducible only when logged in. The problem seems to be `correspondingComponent` being `undefined` here: https://github.com/IFRCGo/go-frontend/blob/develop/app/assets/scripts/components/preparedness/global-preparedness-highlights.js#L25 - this seems similar to another issue which seemed to assume `getPerComponent` will always return an array with at least one member. Is this something that seems straightforward to fix? Are we aware of what the underlying data / consistency issue there might be that is causing this? Thank you!

**Comment by necoline** [comment] 2020-02-04 21:51
I just need to apply the fallback to a default value to a different output of `getPerComponent` by adding the fix in #944

**Comment by batpad** [comment] 2020-02-05 06:43
@nanometrenat @teklal these fixes have been merged and will be on staging in a few minutes. Please test when able. Thanks!

**Comment by teklal** [comment] 2020-02-05 08:27
It works now for me on staging. Thanks!

**Closed** 2020-02-05 11:05 UTC
Labels: Must Fix
