### ISSUE TITLE
the Emergency Appeal (EA) document doesn't pull automatically

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#469] opened 2018-10-02 08:45 UTC
## Issue (by Munu)

The problem is that the Emergency Appeal (EA) document should be automatically pulled to this page https://go.ifrc.org/emergencies/3136 under Appeal Documents. But when you go to Appeal documents you only have the link to download the DREF and the EA document is not available. Essentially we should have at least two documents under this title not one. The emergency appeal  is download able from http://adore.ifrc.org/Download.aspx?FileId=212605  and available on http://www.ifrc.org/en/publications-and-reports/appeals/?ac=MDRNG025&at=0&c=&co=&dt=1&f=&re=&t=&ti=&zo=
 
The Emergency Appeal (MDRNG025) has a different appeal code to the DREF (MDRNG024) so the issue is on MDRNG025. The operations page does not show the EA only the DREF.

**Comment by szabozoltan69** [comment] 2018-10-02 08:49
It's a duplicate of https://github.com/IFRCGo/go-frontend/issues/463

**Comment by szabozoltan69** [comment] 2018-10-02 08:50
I copy the text (by Munu) to https://github.com/IFRCGo/go-frontend/issues/463 and close this.

**Closed** 2018-10-02 08:50 UTC
