### ISSUE TITLE
Outdated list of countries/IFRC offices on personnel deployments

### ISSUE THREAD

**Issue by ElsaRaunioIFRC** [IFRCGo/go-frontend#411] opened 2018-08-16 10:20 UTC
As our Surge team has been advancing with populating the deployments page, an additional issue has emerged. The list of countries and IFRC offices appears to be out of date, dating as back as 2014 when the IFRC was still divided in zones rather than regional offices (and country cluster offices and country offices).

Now, let's say a person working for the Africa Regional Office is deployed to DR Congo. The only current option in the drop down menu is to use Zone Eastern Africa. However, this is very misleading as such zone does not exist anymore.

A full list of current IFRC offices can be found here: https://docs.google.com/spreadsheets/d/1piRJs70B5ruW8ux4sZjlR3sO2uHHF912kU8ZVrSJmKc/edit?usp=sharing
 
In principle, a person can be deployed from any office, so I think all of them should be included in the drop down menu. The names of the offices are in the D column.

Let me know if there's any need for clarification or further information.

**Comment by dereklieu** [comment] 2018-08-22 20:50
Duplicate of #415 - I will close this and elevate that issue.

**Closed by dereklieu** 2018-08-22 20:50 UTC
Labels: Must Fix
