### ISSUE TITLE
[PROD] Field Report and Early Warning Field Report - "actions" not saving or displaying correctly

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#984] opened 2020-03-03 12:21 UTC
## Issue
When a new Field Report or a new Early Warning field report is created, the "actions taken" are not stored or retrieved correctly according to what was submitted.

1. Actions Taken that are selected are not stored correctly in db (example, Field Report 9453 in Staging - “Human remains management and identification” and “Relief/Supply distribution” was saved and pulled through when I was expecting “Camp management” and “Other”)
2. The above then means that when I access a field report via the API or via viewing on the front end the incorrect actions are displayed.  In the case of Early Warning field reports, sections are missing from the view screen altogether.
3. When I go into a Field Report in Edit view, NO actions are ticked (whereas I would expect the actions that had been selected to be ticked).

This was identified in Prod via email from Costa Rica RC relating to Early Warning field report, but my testing in Staging indicates that there are problems with "Event" type field reports also.

## Steps to reproduce
Create a new field report (event type or early warning type), select actions, submit.  Then view onscreen (in both view and edit mode on the front end, and also in the back end) and check that the actions section matches what you have input.

Examples to review (which have screenshots available in Teams):

- "Event" field report - https://dsgoproxyapp.azurewebsites.net/reports/9453
- "Early Warning" field report - https://dsgoproxyapp.azurewebsites.net/reports/9454

API calls:  https://dsgocdnapi.azureedge.net/api/v2/field_report/9453 etc.

## Expected behaviour
Whatever "actions" (whether National Society, IFRC or other RCRC) that I selected in the process of creating the Field Report should display (and display with the same selections) when I go back and view or edit the information.

## Related feature
Early Warning Field Report type was introduced in #833 
Other tickets re fields appearing etc. for Field Reports include #895 and #896 

## Impact
Anyone submitting or viewing field reports (currently ~2 field reports created every 3 days)

## Severity
Functional impact as information is not stored or displayed properly.

## Is there a workaround?
No workaround.

**Comment by nanometrenat** [comment] 2020-03-03 12:55
Comparison Early Action Field Report summary of input vs display for https://dsgoproxyapp.azurewebsites.net/reports/9454 (full screenshots available on Teams)

**Actions taken by National Society**
as displayed on view screen:
•	CTP/Basic needs - INCORRECT
•	First Aid - INCORRECT
•	Camp management - INCORRECT
•	Food aid- INCORRECT
•	Search & Rescue- INCORRECT
What I had input:
Brief description of the Early Actions taken by NS - I have selected Activation / Mobilization of Volunteers, Public Awareness Raising & Sensitization; NFI Distribution; Pre-positioning of Stocks; Food Security & Livelihoods

**Actions taken by IFRC**
as displayed on view screen:
•	Support NS submission to FbA by the DREF or Imminent DREF - correct
•	CTP/Basic needs - INCORRECT
•	Human remains management and identification - INCORRECT
•	Relief/Supply distribution - INCORRECT
What I had input:
Brief description of the Early Actions Taken by IFRC - I have selected Support NS submission to FbA by the DREF or Imminent DREF; Interagency Coordination; Monitor Situation; Movement Coordination

**Actions taken by any other RCRC Movement actors**
as displayed on view screen:
•	CTP/Basic needs - INCORRECT
•	First Aid – CORRECT IN PRINCIPLE BUT DIFFERENT WORDING TO WHAT I HAD SELECTED
•	Damage/Needs assessment - INCORRECT
•	Psychosocial support services - INCORRECT
What I had input:
Brief description of the Early Action Taken by other RCRC Movement - I have selected Rapid Training (including on First Aid); Other; Food Security & Livelihoods; Activation / Mobilization of Volunteers

**Comment by nanometrenat** [comment] 2020-03-03 13:13
@batpad can you please check if this is front end or back end?  Please do assign to @GregoryHorvath for support/maint as required - thanks a lot!

**Comment by nanometrenat** [comment] 2020-03-03 14:07
NOTE:  I can see that the data is different in the "actions" config table between Staging and Prod.
The Early Warning data is in a different order, and there are two options ("Activation of Early Action Protocol" & "Support Activation of Early Action Protocol") that are in Production but not in Staging.

The config data difference should not have an effect on functionality at all - only mentioning it in case people are comparing screenshots between the two environments.

**Comment by batpad** [comment] 2020-03-05 08:48
@nanometrenat - thank you for this report.

There are parts of this that I am able to reproduce and parts not.

 - **Wrong data getting saved and output**: I am unable to reproduce this. When I save Actions, I see them show up correctly as I had marked them, both in the Admin as well as the Field Report view page. Do you think we could do a screen-share or so here? _Maybe_ the issue is a display / layout issue that's causing checkboxes to misalign and look like they are for different labels? I have been unable to reproduce this - i.e. the checkboxes I select in the field report form are being saved and output correctly when I view the field report. I will need some help reproducing this / seeing under what circumstances this occurs.

 - **Actions not appearing when Editing Field Report**: This was a bug :-( - I have got a fix for it here: https://github.com/IFRCGo/go-frontend/pull/988 . I'd like to clarify issue 1 of data being saved incorrectly before merging this for testing.

Thanks again for the detailed report.

**Comment by batpad** [comment] 2020-03-06 11:25
@nanometrenat I have pushed a fix to staging that should fix:

 - Incorrect values being saved, not corresponding to checkboxes being checked
 - Correctly populating checkboxes in the Edit Field Report mode

Will now look at the other tickets around data points missing from the Field Report Frontend view.

**Comment by teklal** [comment] 2020-03-17 14:38
Hey @batpad,
So I've been testing this now and all seems good besides one thing: for both field report types for the selection of whether an information bulletin has been published or it is planned, the data shows incorrectly on the page that is created from the field report.

So it's the section shown in the below screenshot. These are from the same field report (https://dsgoproxyapp.azurewebsites.net/reports/9471), the page that it creates on the left and the form after clicking "Edit Report" on the right.
 ![image](https://user-images.githubusercontent.com/52411237/76865163-925eee00-6862-11ea-8b2a-7117f84c3143.png)

It works as should when "No" is selected but when "Planned" is selected it shows up as "Yes" on the page on the left and if I select "Yes/Published" the section for Information bulletin does not show up at all on the generated page. The same box as initially chosen is still ticked when opening the report to edit.

Let me know if I should clarify this more.

Everything else seemed to work as should. :)

**Comment by batpad** [comment] 2020-03-17 18:40
Thanks so much for the catch @teklal - this should be fixed, as well as the wording for the Potential Date of Impact to Forecasted Date of Impact.

Will double check on the deployment for the phone number fix.

**Comment by teklal** [comment] 2020-03-18 10:01
@batpad tested and works!

**Comment by batpad** [comment] 2020-03-26 12:57
This is tested and in production. What is pending is fixing the data created due to this bug, logged separately.

**Closed by batpad** 2020-03-26 12:57 UTC
Labels: Must Fix
