### ISSUE TITLE
[PROD] Search function not picking up recent emergencies

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#989] opened 2020-03-06 18:08 UTC
## Issue
We have identified that the search function in the top right hand corner of GO front end does not pick up recently-created emergencies.  It does return recently-added Field Reports however.  For example, there have been 9 COVID-related field reports+associated emergencies created so far this week, all the field reports are returned by the search but none of the events.

Similarly, when going into Create New Field Report and searching for an existing emergency to link to (search box labelled PLEASE CHECK FOR, AND LINK TO AN EXISTING EMERGENCY IF AVAILABLE), this search also does not return recent emergencies at all.

The underlying API call is to Elastic Search in v1 of the API (v1 is undocumented, as far as I can tell).  I can't figure out if there's logic in the code that is preventing the desired results from being returned, or if there's a problem on the Elastic Search infra (e.g. apparently it is on a VM, and I'm not sure about caching/scheduled jobs).  OR if in fact there's a problem with the way these emergencies have been set up data-wise.

My example API calls are below:

- returns only very old events:  https://prddsgocdnapi.azureedge.net/api/v1/es_search/?type=event&keyword=cov
- no event filter, correctly returns the field reports though:  https://prddsgocdnapi.azureedge.net/api/v1/es_search/?keyword=cov

Examples from staging, which should return my recent Cook Islands Earthquake test event:
 
- https://dsgocdnapi.azureedge.net/api/v1/es_search/?type=event&keyword=cook
- https://dsgocdnapi.azureedge.net/api/v1/es_search/?keyword=cook

Please investigate so that we can ensure that searching works correctly and events/emergencies can be found.

## Related feature
Old elastic search tickets:

- https://github.com/IFRCGo/go-frontend/issues/248
- https://github.com/IFRCGo/go-api/issues/238
- https://github.com/IFRCGo/go-functions/issues/11 

## Impact
All users searching

## Severity
This prevents the events from being surfaced - e.g. can't Search for the global response (as no field report), can only find it by navigating to it.

## Is there a workaround?
Navigation, if you know where something exists.

**Comment by nanometrenat** [comment] 2020-03-06 18:11
I have a hunch that it might perhaps be to do with whether or not an emergency already has a field report, but haven't been able to confirm that through testing...

**Comment by GregoryHorvath** [comment] 2020-03-11 14:24
Ref: https://github.com/IFRCGo/go-api/issues/631

**Comment by GregoryHorvath** [comment] 2020-03-13 08:50
@nanometrenat I believe this could be closed as well if you find the fix acceptable.

**Comment by nanometrenat** [comment] 2020-03-13 19:11
@GregoryHorvath thank you so much, this is hugely better!

When I go to https://prddsgocdnapi.azureedge.net/api/v1/es_search/?type=event&keyword=cov I am now getting a lot of the recent events returned.

However, can you please investigate why the Global COVID event is not being returned by the above call (emergency id 3972)?  It is definitely being indexed now (yay!) as it is returned by
https://prddsgocdnapi.azureedge.net/api/v1/es_search/?type=event&keyword=global

Thanks for any advice you can give.  Also, we need to look at performance of the search as sometimes it returns quickly and other times it is very slow - but that is an existing issue that I should log as a separate ticket.

**Comment by GregoryHorvath** [comment] 2020-03-15 11:32
> Thanks for any advice you can give. Also, we need to look at performance of the search as sometimes it returns quickly and other times it is very slow - but that is an existing issue that I should log as a separate ticket.

@nanometrenat  My guess would be that since we just made Elasticsearch to reindex everything that’s why some searches will be slower in these first couple of days and it would speed up the more frequent searches soon. But I’m just guessing here, maybe @batpad knows about this more.

**Comment by nanometrenat** [comment] 2020-03-30 19:36
Hi @GregoryHorvath can you please confirm how often the reindexing runs?

ElasticSearch on the front end is not returning all the emergencies I would expect - meaning that users can't link new field reports to existing emergencies if the relevant emergency isn't being returned.

https://prddsgocdnapi.azureedge.net/api/v1/es_search/?type=event&keyword=swed returns eventid 3133 (Forest Fires) but does not return eventid 4120 (https://go.ifrc.org/emergencies/4120) which is the Sweden COVID-19 emergency.

Can you please investigate?  Thanks

**Comment by nanometrenat** [comment] 2020-03-31 11:25
SRV-19938 logged for today's issue - thanks loads

**Comment by nanometrenat** [comment] 2020-05-03 15:19
Hi @GregoryHorvath @batpad can you please advise/confirm how much elapsed time is required before an event can be searched-for in the search box?  and/or how much elapsed time is required after an event is Renamed, for it to show in the search?
Particularly talking about the search box when creating a new Field Report - the one I created in staging hours ago still doesn't appear in search.

Thanks a lot

**Comment by nanometrenat** [comment] 2020-05-12 08:49
Just awaiting the answer to question above then can close - thanks a lot @GregoryHorvath @batpad !

**Comment by GregoryHorvath** [comment] 2020-05-14 06:10
@nanometrenat Sorry for the late reply. Munu had issues with the search not picking up an Emergency a couple of days ago. Checked the logs there were no errors, but reran the reindex anyway and it still didn't show up. But after ~30mins Munu said it finally appeared. I'll need to check on the configuration somehow but my initial guess would be ~5 minutes.

One article saying:
>By default, Elasticsearch periodically refreshes indices every second, but only on indices that have received one search request or more in the last 30 seconds.

But I can see that probably this might've been changed when ES was set up for GO.

**Comment by nanometrenat** [comment] 2020-05-22 12:34
On the call today @GregoryHorvath was looking in the logs for something else and noted that he was seeing 500s around the Elasticsearch endpoint... shall I log a new ticket Greg or just continue this existing Elasticsearch one?

**Comment by GregoryHorvath** [comment] 2020-05-22 13:05
@nanometrenat I think it's okay to keep it here so we can easily backtrack the steps done and remaning.

**Comment by nanometrenat** [comment] 2020-05-22 18:48
If the elasticsearch doesn't get updated promptly when an emergency is deleted (via "gardening") then  it can cause errors submitting Field Reports - e.g. https://github.com/IFRCGo/go-frontend/issues/1077#issuecomment-632854934 - so we need to address the rpot cause of Elasticsearch issues.  Thanks heaps for the troubleshooting!

**Comment by GregoryHorvath** [comment] 2020-06-03 14:50
@nanometrenat @teklal https://github.com/IFRCGo/go-api/pull/757 This is not deployed to staging. From now if someone deletes a Field Report, Emergency, etc which have an ElasticSearch index, then should also be deleted from the ElasticSearch database as well and should immediately not show up in searches.

Connected: https://github.com/IFRCGo/go-frontend/issues/1077#issuecomment-632854934

> If the elasticsearch doesn't get updated promptly when an emergency is deleted (via "gardening") then it can cause errors submitting Field Reports - e.g. [#1077 (comment)](https://github.com/IFRCGo/go-frontend/issues/1077#issuecomment-632854934) - so we need to address the rpot cause of Elasticsearch issues. Thanks heaps for the troubleshooting!

**Comment by GregoryHorvath** [comment] 2020-06-10 09:07
@nanometrenat @teklal Upped the interval for when the Elasticsearch fires from `150ms` to `500ms`, **it's now on staging**. It could take ~half a second more for it to start getting the search results, but also because of this now it doesn't try to query 2-3 searches at once so it should consistently get those results. The only thing I noticed that it still struggles a bit to do it while the rest of the page is also loading at first.

cc @batpad

**Comment by nanometrenat** [comment] 2020-06-11 09:52
> The only thing I noticed that it still struggles a bit to do it while the rest of the page is also loading at first.

@GregoryHorvath @batpad that is a TOP TIP and explains a lot of my search issues - really often I go to the homepage then just start typing the page I want to go to and the search doesn't work (just keeps whirling).  It is probably because the page hasn't finished loading.  I wonder if there is any way we can prioritise search to work regardless of whether the rest of the page has loaded?  Given that what is still loading is generally invisible (as is further down the page rather than in the part of the page that you can see onscreen when you first arrive) the user wouldn't necessarily be aware that loading is still happening.

**Comment by GregoryHorvath** [comment] 2020-06-11 12:36
@batpad You're more knowledgeable about this than me, there should be a way to like, let's say disable(?) the search box or something until everything else does its thing?

Just added a smaller timeout for the Emergency dropdown on the 'Create Field Report' page too, it's deploying to staging right now, so should take only a couple of minutes to be live there.

**Comment by GregoryHorvath** [comment] 2020-06-19 09:37
Made Elasticsearch into a 4 cluster for staging which helped with the performance as well as adding timeouts on the frontend.
Now deleted records are also deleted (https://github.com/IFRCGo/go-api/pull/757) from the Elasticsearch database which should help with newly added records so they don't conflict.

All deployed to staging. The change to a clustered Elasticsearch infra should be done to production as well, when we do a deployment with the changes (and the reindexing being ran after).

**Comment by nanometrenat** [comment] 2020-07-29 12:15
Searching still wonky in Test and Prod - I am not sure whether this ticket (#989) or #1353 is best to track

**Comment by nanometrenat** [comment] 2020-08-13 09:51
This specific ticket relates to contents of what results are returned.  However as per comment on https://github.com/IFRCGo/go-frontend/issues/1353#issuecomment-673380320 there is still a wider problem of no results being returned in both Staging and Production.

**Comment by GregoryHorvath** [comment] 2020-09-01 09:49
Now the indexing of new/updated records are happening every 5 minutes alongside with sending out notifications about them. Sometimes this seems to fail for yet unknown reasons, which might be the cause of why some are missing from the search.

I suggest we rewrite the indexing so it would happen as the objects are created/updated (for example changed Emergency name), and removed when an object is deleted. @batpad 
The deletion part already happens here [pre-delete signal](https://github.com/IFRCGo/go-api/blob/51063b20b9c088a5f0751a75042004cf1f4611d3/api/receivers.py#L129-L139), although this might need some adjusments too that if if fails to reach the ES server it retries a couple of times.

**Comment by jhenshall** [comment] 2021-01-13 13:20
This issue has raised it's head again. Current example is when searching for Storm Filomena, only the field reports are returned in search and not the emergency: 
![image](https://user-images.githubusercontent.com/6359748/104457020-622acd80-55a1-11eb-8e92-b15ec55777e2.png)

As with the original issue, this is particularly frustrating for adding new field reports to existing emergencies - where the `PLEASE CHECK FOR, AND LINK TO AN EXISTING EMERGENCY IF AVAILABLE` search box returns no results, so the users are understandably creating new emergencies, which then means more gardening.

From some vague testing, I actually couldn't get any emegencies to appear in search that had been created from field reports. Only by searching for 'GDACS' did I get any results - but that is far from conclusive.

cc @GregoryHorvath @batpad @tovari

**Comment by GregoryHorvath** [comment] 2021-01-13 13:35
@jhenshall Ran a reindexing, now the Emergency should show up as well. I'll check around the logs to see if there's any hint why that Emergency was missing from the search.

**Comment by jhenshall** [comment] 2021-08-10 10:02
Just stumbled on this ticket. Safe to close @batpad @tovari ?

**Closed** 2021-08-10 15:00 UTC
