### ISSUE TITLE
[Staging] New field report - Status radio button should be reactivated

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1584] opened 2020-09-16 09:35 UTC
## Issue
*If I choose "COVID-19 Related Event" (Yes), the Status (early action) is grayed out. If I then choose COVID Relevant (No) the Status (early action)does not become available*

## URL
*https://dsgoproxyapp.azurewebsites.net/reports/new*

## Steps to reproduce
*If I choose "COVID-19 Related Event" (Yes), the Status (early action) is grayed out. If I then choose COVID Relevant (No) the Status (early action)does not become available*

*If applicable, add screenshots to help explain your problem.*

## Expected behaviour
*Early warning radio button should be selectable again.*

## Related feature
*Please cross-reference the build item to which this relates, if known*

## Criticality/Urgency
*Important*

**Comment by batpad** [comment] 2020-09-16 14:00
@tovari unfortunately, this issue has a bit of a history and is non-trivial to fix.

The problem is that when the user selects COVID-19, we auto-select `Epidemic` as the Disaster Type. Now when the user unselects COVID-19, resetting the disaster type is really awkward. In this case, if you change the Disaster Type to something other than Epidemic, you will be allowed to select Early Warning. With the changes to the field report for Epidemics, it was decided that for the Epidemic Disaster Type, we would enforce them to be of the `Event` type.

We had proposed a different UI to make the hierarchical ordering of decision making more clear to the user, but I know there was a bit of back n forth and it was decided to go with this approach and live with this issue, as the user has two simple work-arounds: to reload the page or change the Disaster Type.

Happy to discuss this in more detail and go over the history here, but for now I would mark this as a known issue and "wontfix".

**Comment by nanometrenat** [comment] 2024-03-18 20:32
Obsolete, no more Covid FRs

**Closed by nanometrenat** 2024-03-18 20:32 UTC
