### ISSUE TITLE
[Prod] Banner - please remove the Survey banner 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1675] opened 2020-11-18 18:35 UTC
Please remove the GO Survey banner from the top of the site.
There is no request to replace it with another banner, it can be removed.

**Comment by GregoryHorvath** [comment] 2020-11-19 08:59
@tovari Please check around if everything works without the banner: https://ifrc-go-minor-remove-banner.surge.sh/

@batpad @geohacker Europe's page is def. not working for example, but not because of the banner removal (https://ifrc-go-minor-remove-banner.surge.sh/regions/3#operations). Most probably these get `Infinity` or `-Infinity` as a value as I've noticed one time.
```
Error: Invalid LngLat latitude value: must be between -90 and 90
    at new o (mapbox-gl.js:139)
    at Function.o.convert (mapbox-gl.js:139)
    at o.setSouthWest (mapbox-gl.js:141)
    at new o (mapbox-gl.js:141)
    at Function.o.convert (mapbox-gl.js:141)
    at t.fitBounds (mapbox-gl.js:452)
    at a.value (main-map.js:206)
    at a.value (map-component.js:74)
    at is (react-dom.production.min.js:212)
    at hu (react-dom.production.min.js:255)
```

**Comment by batpad** [comment] 2020-11-25 05:34
This is done and in production. Marking as Ready for UAT, please move to `Done` when confirmed.

**Comment by batpad** [comment] 2020-12-08 08:18
I am closing this as it's moved to Done and in production. @tovari please re-open if needed.

**Closed by batpad** 2020-12-08 08:18 UTC
Labels: feature
