### ISSUE TITLE
Notification Read more link. 

### ISSUE THREAD

**Issue by mmusori** [IFRCGo/go-frontend#826] opened 2019-09-16 08:33 UTC
## Issue
The read more link on the notification email for Laos Podul floods (issued on 11/09/2019) does not redirect to the emergency page but to the home page. This issue is difficult to reproduce since on My laptop (Munu) it works correctly in chrome. On Luke and JEss's laptops it redirects to the home page in chrome as well. 
![Notifications](https://user-images.githubusercontent.com/7780809/64943730-d437b900-d86c-11e9-8497-8c96704080b8.jpg)
From the screenshot you can see that the link points to go.ifrc.org

## Steps to reproduce

You can check your received notification emails or I can forward the two examples of where it works and where it does not work. 
## Expected behavior

From the notification email I have the link is correct see below and this is how it should work. 
![Notification 2](https://user-images.githubusercontent.com/7780809/64943930-47d9c600-d86d-11e9-8400-930fda7bde95.jpg)

**Comment by szabozoltan69** [comment] 2019-09-16 08:47
The operation (in database terminology: appeal) and the fieldreport + event (which leads to the appropriate emergency) has different role in notifications.

Here is the relevant code part: https://github.com/IFRCGo/go-api/blob/master/api/management/commands/index_and_notify.py#L133-L135
The appeals, which has no paired event **or needs confirmation** leads only to the frontend opening page. This is the intended behaviour. This "needs confirmation" condition can be omitted (but I do not advise). The other condition, the "has paired event" can not be omitted (because if no event to be paired then no page to be shown).

**Comment by szabozoltan69** [comment] 2019-09-16 08:52
@mmusori  – this appeal needs confirmation, that is why the link do not show any specific emergencies:

![needs_confirmation](https://user-images.githubusercontent.com/6050643/64945031-00a10480-d870-11e9-93b0-275fc89710f2.png)

**Comment by mmusori** [comment] 2019-09-25 12:06
Hi Zoltan, 
So that I get it correct. If a DREF/Appeal (Operation) is posted without an emergency event linked to it we need to go an either pair it with an event or link the 'Needs confirmation' to create an event/emergency? So for instance the Laos Floods did not have and Emergency associated with it either because they were not paired or there was no Field Report or GDACS alert?

**Comment by szabozoltan69** [comment] 2019-09-25 12:56
Yes, you are right, Munu, in both aspects.

**Comment by nanometrenat** [comment] 2020-01-17 13:57
Consulted with @mmusori Closing this ticket, thank you for your work!

**Closed by nanometrenat** 2020-01-17 13:57 UTC
Labels: It is a feature
