### ISSUE TITLE
UI Elements - Update

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1325] opened 2020-06-10 10:02 UTC
https://github.com/IFRCGo/go-frontend/issues/1206
https://github.com/IFRCGo/go-frontend/issues/1201
https://github.com/IFRCGo/go-frontend/issues/1203
https://github.com/IFRCGo/go-frontend/issues/1208
https://github.com/IFRCGo/go-frontend/issues/1324

**Comment by mariam-yu** [comment] 2020-06-10 10:11
@LukeCaley @batpad Here are some UI suggestions for various UI elements. We combined several elements into one issue and one mockup, awaiting your feedback.

https://projects.invisionapp.com/share/8FXCLVKEY6C#/screens/418255283_4-1_GO_Emergencies

1 - **Key numbers and header space:** We are proposing to narrow down the key numbers and include them in the reduced header. This way they are a part of the header and, at the same time, take less space.
2 - **Highlighted Operations**: this module got an upgrade with a more visible graph, numbers not wrapping, and full title shown. We also have a variation for 4 cards. Lastly, we are proposing to make the entire card clickable and interactive on hover (first one is as example).
3 - **Map/Table combo**: We are proposing to greatly reduce the map size and have a combination styling with the table to make sure it's clear that the filters apply to both. We also have cleaned up table styles to be used across.
4 - Filter bar: There is a styling proposal for the filter bar to include the dropdowns, export icon, search, and any other functionality that may be applicable to be used on the tables, but also across the platform wherever applicable.

**Comment by LukeCaley** [comment] 2020-06-15 21:23
Thanks @mariam-yu 
**1 - Key numbers and header space:** Looks good
**2 - Highlighted Operations:** Looks good.  The 'clickable' element is missing from the wireframes however.
**3 - Map/Table combo:** Makes sense but requires some significant dev work to make the filters drive the table, which is not currently the case @batpad 
4 - Filter bar: Looks really good. Needs further scoping around a. what is exported and b. consideration of other filters (size of emergency funding requested, emergency 'source', i.e. GDACS/Field Report, etc)

**Comment by mariam-yu** [comment] 2020-06-16 16:20
@LukeCaley Great thanks.
2 - Please see here: https://projects.invisionapp.com/share/8FXCLVKEY6C#/screens/417294996 We also updated some items on the homepage (e.g. graphs, etc.)
4 - Sounds good. Would be good to scope out all the filter possibilities. We can do it on wireframing level - identify what the filters should contain. It's quite updated on wireframes; so, the team can comment directly there for all the pages.

**Comment by mariam-yu** [comment] 2020-06-24 13:15
@imohkay Zeplin is updated. We added/are adding some of the pages where those elements appear above, but some of them are quite throughout (tables, filters, spacing etc.). For spacing, we could use that with the overall page layout ticket that we will create. Thanks!

**Comment by imohkay** [comment] 2020-06-24 14:34
@mariam-yu Thank you :) I'll get to work tomorrow or so and ping you if I have any questions/doubts..

**Comment by imohkay** [comment] 2020-07-14 08:59
@mariam-yu @maisa-yu 
In preparation for the mid-July launch, I just wanted to run over the UI changes that have been applied to the site.
1. Key Numbers across the site match the Zeplin design
2. Highlighted Operations widget matches the Zepling design (the position of the widget will be moved at a later stage on the home page, since it will require a fair bit of restructuring of the relevant components)
3. The tables broadly match those on Zeplin (minus the bottom borders touching the edges). The search and filters for the same will be implemented in a future release, since they have to be discussed with the dev team.
4. The page headers are all centered and have the relevant letter spacing. We will fix the issues on pages with action buttons in the header (like Country) in a future release.

Could you let us know if there are any UI blockers for the mid-July release?
FYI, I am working in a separate branch to incorporate a holistic styling across the site, where the pages will be far more consistent in layout, styles and components. However, that will go in a later release. We just need to ensure there are no glaring UI issues for the current release.

**Comment by batpad** [comment] 2020-07-14 09:10
Thanks @imohkay !

> Highlighted Operations widget matches the Zeplin design (the position of the widget will be moved at a later stage on the home page, since it will require a fair bit of restructuring of the relevant components)

I feel uncomfortable going ahead with a production release without this done (i.e. moving Highlighted Operations to its intended place in the UI) - let's discuss and perhaps this is something I can take on / help with.

Apart from this, things look really good to me, of course will be great to get a final design audit from @mariam-yu and see if there's anything that's a blocker for this release, or if it would be covered when you are doing the holistic styling across all pages.

**Comment by mariam-yu** [comment] 2020-07-14 11:17
@imohkay @batpad Can you please share the link to where we should review the final updates? The staging site currently looks a bit off, the margins look too narrow and the highlighted operations are all the way on the bottom. https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/417294996 (for comparison).

Shall we just compare the single elements? Not sure also what will be pushed to production. I think this should be updated before that. Also, could we remove the word Language from the top Nav? Thanks!

**Comment by imohkay** [comment] 2020-07-14 12:15
@mariam-yu @maisa-yu 
This is the link: https://dsgoproxyapp.azurewebsites.net/
@batpad will ensure the highlighted operations are moved to the correct position before this release
The language translation dropdown in the site header will be hidden, since the translation happen in a later release.
Could you let me know which are the margins which are too narrow? Thank you :)

**Comment by mariam-yu** [comment] 2020-07-14 13:25
@imohkay If you look between the staging and this link https://projects.invisionapp.com/share/HGX94BX3EJA#/screens/417294996

You can see that the top key numbers and Active Operations map margins are too narrow. Surge on the bottom has the previous margins. Our proposal (in the link) is to make it somewhere in between the surge and what you have now on the top section. Either way, it should be standard across the page. Please let me know if makes sense.

**Comment by mariam-yu** [comment] 2020-07-14 13:25
<img width="1440" alt="Screen Shot 2020-07-14 at 3 04 28 PM" src="https://user-images.githubusercontent.com/60006476/87430975-3cb70a00-c5e6-11ea-8d7d-afc84e19fdad.png">
<img width="1437" alt="Screen Shot 2020-07-14 at 3 04 45 PM" src="https://user-images.githubusercontent.com/60006476/87430988-417bbe00-c5e6-11ea-9c8c-fe56ec638452.png">

**Comment by mariam-yu** [comment] 2020-07-14 13:26
<img width="1440" alt="Screen Shot 2020-07-14 at 3 04 56 PM" src="https://user-images.githubusercontent.com/60006476/87431019-4d678000-c5e6-11ea-9736-9d8ed51d8fab.png">
<img width="1435" alt="Screen Shot 2020-07-14 at 3 05 17 PM" src="https://user-images.githubusercontent.com/60006476/87431031-51939d80-c5e6-11ea-87bc-0c5af05b7530.png">

**Comment by imohkay** [comment] 2020-07-14 15:54
@mariam-yu are you referring to the horizontal margins? Or the width of the container?

**Comment by mariam-yu** [comment] 2020-07-14 16:38
@imohkay referring to the page margins on the right and left - so the space between the end of the page and the containers.

**Comment by imohkay** [comment] 2020-07-15 10:36
@mariam-yu Just to clarify, the maximum width of the current site is 1420px (except for the full-bleed sections).
However, on Zeplin, the overall width appears to be in the range of 1200px (30-40 pixels up and down for sections with bigger margins like key numbers). For the new branch I'm working in (which won't be reflected for the next launch), should I bring down the overall width of the site to 1200px from 1420?

**Comment by imohkay** [comment] 2020-07-15 14:08
@maisa-yu @mariam-yu https://dsgoproxyapp.azurewebsites.net/ has been updated with highlighted operations at the top.
I've reduced the size of the key numbers, but am planning to work on the proper margins and spacing for a future release (not the current one). A lot of the code is getting refactored styling-wise, and it would be great if we could push all those changes together. My only concern is currently things breaking across the site... Let me know if this works for now?

**Comment by mariam-yu** [comment] 2020-07-15 14:16
@imohkay Let us do a proper audit and get back to you. In the meantime, I think it's better to have the previous margins rather than these ones, as the contrast might be too big with other elements on the page. Would it be easy to readjust? I will respond to you shortly about your question about page sizes. Checking with our UI designer.

Also, do you mind updating the font sizes on Highlighted Operations? We pumped up the sizes a bit as they all looked quite small. Thanks!

**Comment by maisa-yu** [comment] 2020-07-15 14:19
> @mariam-yu Just to clarify, the maximum width of the current site is 1420px (except for the full-bleed sections).
> However, on Zeplin, the overall width appears to be in the range of 1200px (30-40 pixels up and down for sections with bigger margins like key numbers). For the new branch I'm working in (which won't be reflected for the next launch), should I bring down the overall width of the site to 1200px from 1420?

@imohkay On zeplin the margins are 1440px. Could we just reduce the width to 1420px (just removing 10px from each side)? Thanks!

**Comment by mariam-yu** [comment] 2020-07-15 14:33
@imohkay To add to Maisa's comment, what we have is a full width of the page 1440px with a 100px margin on each side, which makes the content itself 1240px. How was it before? Can you clarify? And is this doable?

**Comment by nanometrenat** [comment] 2020-07-15 15:09
Hi, request from me - as per the GO call - I know that the GO platform is not optimised for mobile, and I know that mobile optimisation is not in scope for this particular round of changes, which is fine - however it would be GREATLY appreciated if the work being done at the moment could always be keeping the mobile user experience equivalent-to-current (if not improving it!!) rather than in any way making it worse.  Thanks all for your help with this!

Note also that the key figures on the homepage are regularly screenshotted and used in various communications so great to make sure that will still look OK too.  Cheers.

**Comment by batpad** [comment] 2020-07-15 15:28
> Hi, request from me - as per the GO call - I know that the GO platform is not optimised for mobile, and I know that mobile optimisation is not in scope for this particular round of changes, which is fine - however it would be GREATLY appreciated if the work being done at the moment could always be keeping the mobile user experience equivalent-to-current (if not improving it!!) rather than in any way making it worse. Thanks all for your help with this!

The styling restructuring to support RTL, due for the mid-August release along-with translations, should greatly improve the experience on mobile, or at the very least, make it much easier to work toward. @imohkay please add if there's specific comments around that, but I know from conversations that this should hugely improve some of the styling handling for smaller screens.

For this release, if something looks especially broken, please do flag and we can see what we can do.

> Note also that the key figures on the homepage are regularly screenshotted and used in various communications so great to make sure that will still look OK too. Cheers.

Is there something specific off about the key figures off or wrong on staging right now? They should be fairly accurately matching the new designs.

**Comment by nanometrenat** [comment] 2020-07-16 09:23
> Is there something specific off about the key figures off or wrong on staging right now? They should be fairly accurately matching the new designs.
I haven't been involved in or seen the new designs but if staging is reflecting what is designed then great thanks a lot :)  Was only mentioning the key figures screenshots because they are used off-GO as well, many cheers.

**Comment by LukeCaley** [comment] 2020-08-04 20:23
Some small elements in the Field Report submission form which require attention before release:

**Contacts** appears as a header on the Actions tab for the Field Report submission form - should read Actions taken as previously 
![contacts-error](https://user-images.githubusercontent.com/7791954/89338857-7dfa8100-d69d-11ea-9753-f5566072bbb5.JPG)

**Response** contains duplicate information.  The wording needs to be reverted to current language with no redundancy/repetition
![response-error](https://user-images.githubusercontent.com/7791954/89339320-42ac8200-d69e-11ea-9264-6dadc23b1243.JPG)

In this case an event FR with type `fire` used as example and **further testing required** for all different FR form scenarios (early warning, epi, covid, etc) to ensure similar text errors are not present in other FR form submissions @karitotp @imohkay 

Final point re FRs which might require separate ticketing for backlog (and is certainly not high priority) is that the Field Report final page still looks clunky.  There seems to me little value in continuing to surface empty fields such as three sources for deaths, missing etc.  @mariam-yu it would be good to hear your thoughts on a more elegant and space-efficient means of displaying this info, with the goal to avoid unnecessary requirements for users to scroll further down the page if possible to be avoided?
![field-report-error](https://user-images.githubusercontent.com/7791954/89340294-cca91a80-d69f-11ea-9088-8867e1ba36c9.JPG)

**Comment by batpad** [comment] 2020-08-05 06:52
Thank you so much for the catches on the field report form, @LukeCaley - these should have been caught.

Quick question: I noticed also that in the Response section, the `Contacts` heading for the Contacts subsection was missing / removed. I tried looking around in Invision and Zeplin but could not find the designs for this section. I am adding back the Contacts heading, as it seems to have been removed inadvertently.

Work in progress PR here: https://github.com/IFRCGo/go-frontend/pull/1494 just waiting for @imohkay to help style the Contacts heading, and this should be good to merge to the Release branch. Thanks again @LukeCaley for catching these.

Re: The Field Report display page. I think there's a general design guideline to "hide things that have no data". If we should ideally follow the same logic here, I think it makes sense to create a larger ticket to "hide things that have no data" and then work through each of these things. Of course, there could also be other design suggestions for the field report page (agree that even with the changes, it still looks a bit clunky, though I don't have an idea / opinion on a design solution here).

**Comment by batpad** [comment] 2020-08-05 08:02
Made the following fixes and have deployed to the Release branch: (https://ifrc-go-release-v4-3-11.surge.sh/)

 - Fixes heading in Actions section to say Actions Taken instead of Contacts
 - Fixes repetition of text in Planned Response subheading
 - Adds back Contacts as a heading in Response section.

**Comment by karitotp** [comment] 2020-08-05 16:03
> In this case an event FR with type fire used as example and further testing required for all different FR form scenarios (early warning, epi, covid, etc) to ensure similar text errors are not present in other FR form submissions @karitotp @imohkay

I gave a look to the other types of FR, in all cases is displaying CONTACTS as a header in Action tab, and a redundant text in Response tab.

Other thing that I came across many times was the grey screen, this happen when I modified my selections between Early warning and Event option, modifying the selection of the Covid related event (beetwen yes or not) and changing disaster type.

cc. @batpad

**Comment by guipizzini** [comment] 2020-08-06 08:42
@batpad I get the gray screen as well and the CONTACTS as a header. In addition, the "infobox" once you click the box appears but then it stays there. This means that you need to re-click to remove and if you do not do so, it simply stays there and you can click the other infobox, which then overlaps making it not a nice experience at all. Is this normal? Other than that, all looks good.

**Comment by batpad** [comment] 2020-08-06 09:01
I am unable to reproduce these issues with the Field Report. @guipizzini @karitotp is this reproducible on https://ifrc-go-release-v4-3-11.surge.sh/reports/new ? Would be great to get specific steps to reproduce. If this is reproducible on the release branch, we probably need to figure it out before release?

**Comment by batpad** [comment] 2020-08-06 11:49
@guipizzini could you check these issues again, they should now be fixed on staging as well as https://ifrc-go-release-v4-3-11.surge.sh/reports/new .

Of course, this is apart from the info-box issue, which as discussed, not being a regression, we will tackle in a future release.

**Comment by guipizzini** [comment] 2020-08-06 12:00
Cleared to go, seems all working fine and fixed. Thanks @batpad and noted on the infobox issue.

**Comment by karitotp** [comment] 2020-08-06 15:07
> Would be great to get specific steps to reproduce. If this is reproducible on the release branch, we probably need to figure it out before release?

@batpad,  the gray screen appears by following these steps:

- Fill the form for an event related to covid (I fill just the first tab of CONTEXT  form and I continue to the other tabs).
- Then,I back again to the CONTEXT tab to change the event for a no related to covid event and also change the disaster type (for example, Flood).
- Then I continue to the tab of SITUATION (page works correctly until this step) but when you continue to ACTION tab the page is turn grey.

Same in case I change from Early Warning option to an Event.

**Comment by nanometrenat** [comment] 2020-08-06 15:40
> @batpad, the gray screen appears by following these steps:
> 
> * Fill the form for an event related to covid (I fill just the first tab of CONTEXT  form and I continue to the other tabs).
> * Then,I back again to the CONTEXT tab to change the event for a no related to covid event and also change the disaster type (for example, Flood).
> * Then I continue to the tab of SITUATION (page works correctly until this step) but when you continue to ACTION tab the page is turn grey.
> 
> Same in case I change from Early Warning option to an Event.

I believe that scenario was accepted when the COVID-19 Field Reports were introduced.  It is not a usual situation that someone would change their mind about those critical settings.  I therefore suspect the grey screens are not specific to this UI elements build.

**Comment by nanometrenat** [comment] 2020-08-07 14:54
Accepting risk, going to Production now

**Comment by nanometrenat** [comment] 2020-08-12 08:26
I am closing this mega-ticket as these changes are now in Production - if any further changes are needed they should be logged as separate tickets!

**Closed by nanometrenat** 2020-08-12 08:26 UTC
