### ISSUE TITLE
an issue with the data automation from the API

### ISSUE THREAD

**Issue by omniscjencja** [IFRCGo/go-frontend#468] opened 2018-10-02 08:17 UTC
## Issue (by Guido) 

For the Bangladesh Operation we have around 16M CHF displayed both on the API as much as on the front end.
 
However, the accurate figure as of today for the funding level is more than 18M which makes our front end inaccurate and more worrying, it seems to be that the API is not working properly.
 
I’ve tried to manually update the Appeals value in the Django Framework for this event but it would not allow me to save saying there is an error which is not highlighted.

MDR Code for the Operation of concern: MDRBD018

**Comment by dereklieu** [comment] 2018-10-10 21:30
This appears to be a duplicate of #459.

**Closed by dereklieu** 2018-10-10 21:30 UTC
Labels: Must Fix
