### ISSUE TITLE
COVID-7 // Merge emergencies 

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1010] opened 2020-03-15 21:22 UTC
**Problem**
Multiple emergencies are sometimes created for the same situation.  If field reports are associated with these emergencies it then becomes problematic to reconcile

**Proposed solution**
Back end function to merge emergencies and auto-redirect

**Comment by GregoryHorvath** [comment] 2020-03-16 08:57
@LukeCaley I see 2 ways to go here:
- Keep only 1 emergency (probably the older one) and add all information from the newer one to it.
- Keep both emergencies but add all information from the newer one to the older one.

> If field reports are associated with these emergencies it then becomes problematic to reconcile

Agreed, this also raises questions like:
- What to do with the connected appeals and such? _(keeping both emergencies could lead to an issue with the ingested appeals I'd assume, but this is just a blind guess)_
- What to do with numeric values, ex. `Num injured`s would be added together or the higher one should be kept? Same with dates, etc.

**Comment by LukeCaley** [comment] 2020-03-24 12:44
@nanometrenat can you elaborate on this issue?

**Comment by nanometrenat** [comment] 2020-03-25 00:37
Hi, as this is a manual process I would suggest it's fine that the user chooses which emergency to keep as "master".  The user can move the field reports over to the "master" (or if it's easy to automate then great, but not a show-stopper, it's fine for the user to do the re-mapping of field reports to emergencies like we do at the moment).

I would expect that the user chooses to keep the emergency with an Appeal - it's fine if they are blocked from deleting an Emergency while there is an associated Appeal, as they can always re-map it before going back and deleting.

The key thing here is to be sure that any URLs from the old emergency then point to the emergency that is kept (rather than going nowhere).  And that any data from the old emergencies isn't included in calculations e.g. number of emergencies in last 30 days or since forever or whatever.

Costa Rica is an example of a country where we'll have to do lots of merging/deleting over the coming few days.

Thanks

![image](https://user-images.githubusercontent.com/33625192/77489700-31727f80-6e39-11ea-82a6-54087ed20b28.png)

**Comment by GregoryHorvath** [comment] 2020-03-25 11:13
@nanometrenat I just want to make sure I understand every part.

1. Choose a `master` Emergency and select the ones to merge
2. Connect every Appeal / Field Report to the `master` Emergency (other than that don't overwrite any data of the `master` from the other ones)
3. Delete the merged Emergencies so they won't be included in statistics at the top part of some pages

* Would this be a frontend workflow or a backend one?
* What type of auth would be needed to merge Emergencies? (only Field Reports have a field for the user who created them, which can be used by the frontend)

cc @LukeCaley

**Comment by GregoryHorvath** [comment] 2020-04-01 13:22
Pushed this to staging.
cc @teklal 

Basically there is a new field for every Emergency called `Parent Emergency`, and if it's filled out we consider that Emergency/Event as "merged" and it shouldn't appear on the frontend anywhere.
![image](https://user-images.githubusercontent.com/30079559/78141912-747db580-742c-11ea-81f8-82585a72fafd.png)

**Comment by teklal** [comment] 2020-04-01 20:36
Thanks @GregoryHorvath. After merging the merged emergency does not show up on the frontend anymore i.e. in the recent emergencies counts.

A few comments though still:
- The URL redirect from the "merged" to the "parent" does not seem to work (I merged https://dsgoproxyapp.azurewebsites.net/emergencies/3907#details into https://dsgoproxyapp.azurewebsites.net/emergencies/3911#details, but the first link instead of redirecting to the second gives a blank page)
- I was able to do this even with a user that is not a superuser
- I was able to merge an event that had appeals linked to it, I think there should be an error raised until all appeals and field reports that have been mapped to that emergency have been manually re-mapped

**Comment by GregoryHorvath** [comment] 2020-04-06 14:05
@teklal Both the `superuser` and the `redirect` parts are deployed to staging.

**Comment by teklal** [comment] 2020-04-07 09:59
Great - tested and the redirect and superuser parts work now!

**Comment by teklal** [comment] 2020-04-08 07:43
So the problem I'm still experiencing is that sometimes when opening an emergency on the backend the "Parent Emergency" box does not appear until having refreshed the page a few times. This is not specific to one emergency but doesn't either happen every time (haven't been able to figure out a pattern, sorry, maybe related to superuser check?)

Also: As discussed on the call - add a text/help box reminding the user to map all linked snippets, response documents, field reports and/or appeals to the parent emergency page.

**Comment by GregoryHorvath** [comment] 2020-04-08 14:43
@teklal Deployed the latest fixes using https://github.com/IFRCGo/go-api/pull/661 to staging.

The 'Parent Emergency' for `superuser`s part is really strange, I could only reproduce it once and it happened when I started to refresh the page so frequently. It feels like the logic which handles fields to be read-only or not happens after some of the page is already loaded so it's really weird. And after closing the page and reopening it the issue went away. (not to mention sometimes the read-only version of 'Parent Emergency' showed up twice for me when the editable field didn't)

cc @thenav56 @frozenhelium @batpad

**Comment by teklal** [comment] 2020-04-15 08:34
Thanks @GregoryHorvath, saw the help box, great!

> The 'Parent Emergency' for superusers part is really strange, I could only reproduce it once and it happened when I started to refresh the page so frequently. It feels like the logic which handles fields to be read-only or not happens after some of the page is already loaded so it's really weird. And after closing the page and reopening it the issue went away. (not to mention sometimes the read-only version of 'Parent Emergency' showed up twice for me when the editable field didn't)

Has the above been addressed?

**Comment by GregoryHorvath** [comment] 2020-04-15 08:47
> Thanks @GregoryHorvath, saw the help box, great!
> 
> > The 'Parent Emergency' for superusers part is really strange, I could only reproduce it once and it happened when I started to refresh the page so frequently. It feels like the logic which handles fields to be read-only or not happens after some of the page is already loaded so it's really weird. And after closing the page and reopening it the issue went away. (not to mention sometimes the read-only version of 'Parent Emergency' showed up twice for me when the editable field didn't)
> 
> Has the above been addressed?

@teklal Well we tried to investigate with Sanjay in a call but couldn't find much, it was most probably because of some slow connection (between servers or client-server, etc). It occured to me once as I mentioned and I still don't know why it happened but at that time there were other fields which acted strangely too, like going into read-only mode only after a second or two after the page rendered (or the other way around).

**Comment by teklal** [comment] 2020-06-08 11:41
Closing as main thing working now in prod (thanks!) and remaining issue ticketed elsewhere (#1299).

**Closed by teklal** 2020-06-08 11:41 UTC
Labels: feature
