### ISSUE TITLE
[PROD] PER:  Preparedness tab does not render in Production

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-frontend#954] opened 2020-01-29 17:30 UTC
## Issue
https://go.ifrc.org/preparedness does not function.
The issue arose after a user had submitted forms A3 and A3-2 for Barbados.

## Steps to reproduce
Log in and click on "Preparedness" at the top of the GO page.

## Expected behaviour
The Preparedness page should load.

## Related feature
PER #953 
PER #950 
PER #952 

As the issue arose after submitting forms A3 and A3-2 this problem may be/is likely to be related to the issues linked above

## Impact
Currently the problem affects all logged in users of GO navigating to the "Preparedness" tab.

## Severity
This should hopefully be fixed with the pending push to production of PER fixes.

## Is there a workaround?
There is no workaround.

**Comment by nanometrenat** [comment] 2020-01-29 18:14
Errors:
TypeError: Cannot read property 'id' of undefined
GET https://prddsgocdnapi.azureedge.net/api/v2/per_ns_phase/?country= 500

**Comment by nanometrenat** [comment] 2020-01-29 18:15
As per Tekla's comment above 
> This should hopefully be fixed with the pending push to production of PER fixes.

However we need to know for sure that this issue will be addressed - can we discuss best plan to check/test the new code will play nicely with the Production data once it is released?  Thanks!

**Comment by batpad** [comment] 2020-01-30 14:24
This looks to be caused by the backend returning a 500 error for this URL: https://prddsgocdnapi.azureedge.net/api/v2/per_ns_phase/?country=

@szabozoltan69 @GregoryHorvath would you be able to help here to check out what might be going on / get some logs from the server if possible? Since this is appearing on production, it's not related to any of the refactor changes, none of which have been merged in, and we haven't done any refactoring or changes of the backend PER code.

@szabozoltan69 @GregoryHorvath if we can get some logs, happy to try and dig through what might be causing this 500. Thanks!

**Comment by nanometrenat** [comment] 2020-01-30 14:46
@batpad @szabolcsgajerifrc @GregoryHorvath could this 500 error be due to the fact that PER Process Phase table is currently empty in Prod?  (this still ought to be handled, but might explain the error).

Re the per_ns_phase API, note that:
* re Production:  if I put any parameters in (e.g. country=1 OR limit=1 or whatever) I get a 200 response, I'm only getting a 500 if there are no parameters at all
* in both test and Prod, if I put in a country parameter that for a country that exists but has no per_nsphase records (e.g. country=26) I get the below response - i.e. 1 record is returned, but with an id of -1 - this is incorrect, as should be count=0 and 0 records returned by that filter.
`{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": -1,
            "country": 26,
            "phase": 0,
            "updated_at": "2011-11-11T00:01:01Z"
        }
    ]
}`
* whereas in both Test and Prod, if I put in a country parameter for a country that does not exist at all (e.g. country=555) I get the expected 0 record result:
`{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}`

So, if you are in agreement, I suggest we not worry too much about the 500 error as that will only occur when there is no phase data in at all, but I suggest we ought to fix the -1 back end API issue.

**Comment by szabozoltan69** [comment] 2020-01-30 15:23
Yes, it's true, that this error comes only when the related PER table is empty. In my local environment for a curl request 'api/v2/per_ns_phase/?country='  I get a nice answer: {"count":4,"next":null,"previous":null,"results":[{"id":5,"country":178,"phase":4,"updated_at":"2019-07-09T08:38:08.491268Z"},{"id":4,"country":82,"phase":2,"updated_at":"2019-07-09T14:15:20.002430Z"},{"id":6,"country":307,"phase":0,"updated_at":"2019-07-17T12:39:16.779484Z"},{"id":7,"country":169,"phase":2,"updated_at":"2019-07-17T12:39:35.581142Z"}]}

And it's also true that a nonexistent country ID also gives nice. I try to find a quick and clean solution...

**Comment by szabozoltan69** [comment] 2020-01-30 16:58
Now there is no API error on https://go.ifrc.org/preparedness - though nothing can be seen (due to the empty PER database).

**Comment by nanometrenat** [comment] 2020-01-30 20:30
Thank you @szabozoltan69 for fixing up the API error, most appreciated.

@batpad the page still doesn't render in Production though - the 500 error is gone but the other error remains:
TypeError: Cannot read property 'id' of undefined ...
    at Array.forEach

Am I correct in guessing that the For Each is probably falling over solely due to no data?  In which case I am happy to close this ticket.  Thanks a lot.

**Comment by batpad** [comment] 2020-02-27 12:09
This looks fixed and tested to me. Feel free to re-open if there are issues @nanometrenat @teklal

**Closed by batpad** 2020-02-27 12:09 UTC
