### ISSUE TITLE
[Staging] Icons missing

### ISSUE THREAD

**Issue by imohkay** [IFRCGo/go-frontend#1468] opened 2020-07-28 05:55 UTC
https://paper.dropbox.com/doc/IFRC-GO-TEST-07-27-R5uoDCI3YpCdQNrdaeA21

All the icons referenced in this document appear locally while testing, so there may be some issues with paths?

**Comment by batpad** [comment] 2020-07-28 07:15
This was a bit strange, seems like a hiccup with the deploy process. Redeploying has fixed the icons now.

**Comment by karitotp** [comment] 2020-07-28 16:12
All icons appear on the page now!

**Comment by nanometrenat** [comment] 2020-07-29 19:38
Not sure if this is related to the one I just logged https://github.com/IFRCGo/go-frontend/issues/1479 ?

**Comment by LukeCaley** [comment] 2020-08-04 19:19
@imohkay @batpad - has the root cause been identified for this bug?

**Comment by nanometrenat** [comment] 2020-08-07 14:56
Closing based on Sanjay's advising that it looks to be a deploy issue, but will reopen if this happens again.

**Closed by nanometrenat** 2020-08-07 14:56 UTC
