### ISSUE TITLE
Notification email 

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#366] opened 2018-07-24 06:56 UTC
## Issue

Email notification of new emergencies (from field reports etc) does not provide key information needed to understand the situation, e.g. country affected, status of response actions taken etc.  A redesign of which fields are pulled in as well as building out standard links is required.  Logging here for phase 3.

![email-notification](https://user-images.githubusercontent.com/7791954/43121842-61b0785a-8f1f-11e8-9099-bbbf59c10e09.PNG)

**Comment by LukeCaley** [comment] 2018-08-21 14:51
The notification email uses a script to produce a friendly greeting, e.g. G'day, : waves : etc. Charming to some but maybe a bit inappropriate for disaster reports.  To be removed and replaced with a standard notification e.g. 'New Field Report' or 'New Emergency'.  

Add a GO logo to the automated email generated.

Turn off reception of multiple notifications for each emergency on a single day so as not to be bombarded if there were subsequent amendments made to a field report for instance.

**Comment by szabozoltan69** [comment] 2018-09-12 10:56
The friendly greeting, e.g. G'day, : waves : etc. are now replaced with some simple row (Dear Sir/Madam). Otherwise this kind of (random) greetings were used only in case of "generic notifications" – the appeals, events and reports used their own template (without these glad wavings).

**Comment by szabozoltan69** [comment] 2018-09-16 06:41
Ready to test

**Comment by LukeCaley** [comment] 2018-10-02 11:53
@szabozoltan69 Also need to double check all hyperlinks are pointing to the right URL.  At the moment the 'view on GO' link points towards for example http://prddsgoproxyapp.azurewebsites.net/emergencies/... and the 'view on admin' points towards a 'Not found' error page

**Comment by szabozoltan69** [comment] 2018-10-03 15:39
Could you @LukeCaley send me an example where the link points towards a 'Not found' error page? I could not reproduce such case. (Only a similar, which was due to the development server run http and the link was https.) | No problem with the prddsgoproxyapp... link, it works fine for me, it shows the relevant message.

**Comment by ElsaRaunioIFRC** [comment] 2018-11-27 12:14
@szabozoltan69 It looks like this problem still occurs. When I click "View on Admin Page", all I get is a "Not found" error.

"View on IFRC GO" is working correctly.
![image](https://user-images.githubusercontent.com/31092591/49081225-67542380-f246-11e8-9bb0-59bc6e049ccd.png)

![image](https://user-images.githubusercontent.com/31092591/49081216-5e635200-f246-11e8-8301-3c6a7c37ab22.png)

**Comment by szabozoltan69** [comment] 2018-11-28 11:32
@ElsaRaunioIFRC Could you please forward me this email? Or please give me some more details, what kind of email is it, and what was the broken link exactly.

**Comment by ElsaRaunioIFRC** [comment] 2018-11-28 12:04
@szabozoltan69 I forwarded you the email.

**Comment by szabozoltan69** [comment] 2018-11-28 12:30
@ElsaRaunioIFRC I fixed it, in a few hours the next emails should contain correct URL-s.

**Comment by ElsaRaunioIFRC** [comment] 2018-11-28 15:07
@ElsaRaunioIFRC Let's test this when we get the next digest. If it works, I'll close the case.

**Comment by ElsaRaunioIFRC** [comment] 2018-11-29 15:42
@szabozoltan69 The problems appear to be solved, at least with the old emergencies. I'm closing this issue and will open again if any problems appear.

**Closed by ElsaRaunioIFRC** 2018-11-29 15:42 UTC
Labels: Phase 2.1
