### ISSUE TITLE
[Staging] Translations - alignment issue when viewing in Arabic

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1560] opened 2020-09-09 07:24 UTC
## Issue
Logged on behalf of @LukeCaley (feel free to add any additional info)

In Staging, if I switch to Arabic language then scroll down the page the page elements jump around (horizontally) as I go down the page - but this seemingly doesn't happen in the Left to Right languages.

## URL
https://dsgoproxyapp.azurewebsites.net/

## Steps to reproduce
Go to staging, scroll down.

Note that it seems to mostly happen when I scroll using the mouse wheel, rather than when I drag down the scroll bar.  Screen recording in Teams (first go down is using scroll bar, second is using mouse wheel - then third time is mouse wheel but in English).

## Expected behaviour
Should scroll smoothly

## Related feature
Translation - e.g. https://github.com/IFRCGo/go-frontend/issues/1253

## Criticality/Urgency
Annoying but cosmetic!

**Comment by nanometrenat** [comment] 2020-09-09 07:45
@batpad the above was in Chrome.  Just tried in Firefox and didn't get any jumpiness on Arabic homepage

**Comment by LukeCaley** [comment] 2020-09-09 07:47
Thanks @nanometrenat !  Confirmed same behaviour when using the mouse wheel.  And, eerily, only when moving slowly...

**Comment by batpad** [comment] 2020-09-09 07:48
Hmm .. the only thing I could find that seemed like it could be the cause of this was something like https://github.com/harvesthq/chosen/issues/447 .

This definitely *seems* like buggy browser behaviour. I'm as yet unable to reproduce. @imohkay do you have any ideas? cc @frozenhelium

**Comment by geohacker** [comment] 2020-09-09 08:01
I just tried this on macos (10.15.6, catalina), chrome (Version 85.0.4183.83 (Official Build) (64-bit)) and couldn't reproduce. [Video](https://www.dropbox.com/s/z4o22wth45nu33h/Screen%20Recording%202020-09-09%20at%201.23.14%20PM.mov?dl=0).

**Comment by batpad** [comment] 2020-09-09 08:03
This bug is looking suspiciously like this bug report on Chrome: https://support.google.com/chrome/thread/41121384?hl=en

**Comment by batpad** [comment] 2020-09-09 08:11
> This bug is looking suspiciously like this bug report on Chrome: https://support.google.com/chrome/thread/41121384?hl=en

For folks who have reported this problem - @LukeCaley @nanometrenat - could you confirm if you are zoomed in to the webpage when this occurs (you can press ctrl+0 to reset your zoom) ?

According to the above linked ticket on Chrome, they say this is fixed with the newest Chrome release - it definitely seems like the bug we are running into is this ticket - if it is indeed this bug, there's likely not much we can do other than hope users update their Chrome soon and this goes away. But to confirm this, we need to:

 - Confirm this is only reproducible scrolling with mouse-wheel
 - Most importantly, that only Chrome is affected (knowing versions of Chrome for folks affected would be great)
 - Confirm this goes away using the workaround mentioned in the ticket - `Try disabling "chrome://flags/#smooth-scrolling", it worked for me.`

If these are true, I am afraid we will need to put this down as a browser bug that is fixed in the latest release.

@karitotp could you please do a bit of testing of this behaviour as well? If you can reproduce the "page jumping" behaviour when Arabic is selected - and if yes, on which browser, etc.

**Comment by geohacker** [comment] 2020-09-09 08:22
In the video I posted above, my browser was actually zoomed in. Just tried with ctrl+0, can't reproduce.
Would also be good to compare browser version with @LukeCaley and @nanometrenat

**Comment by nanometrenat** [comment] 2020-09-09 08:24
I'm using Version 85.0.4183.83 (Official Build) (64-bit) on a normal IFRC laptop (Lenovo T460s)

**Comment by batpad** [comment] 2020-09-09 08:33
I was able to reproduce this on a Windows machine with Chrome v85.0.4183 .

I was able to go to `chrome://flags/` and set the `Smooth Scrolling` option to Disabled. Then, the jumpiness went away. Of course, we cannot ask our users to do this, but this confirms that it is indeed a Chrome bug with this "smooth scrolling" option. It **seems** to also be specific to Windows, but would need to confirm this.

The jumpiness is pretty bad if one is affected. But if we can confirm it is fixed in a Chrome update, my recommendation would be to not try and do anything about this as this is a confirmed browser bug that also affects other webpages, and there is likely no simple fix on our end.

**Comment by batpad** [comment] 2020-09-09 08:41
@imohkay - this maybe worth looking at to see if there's any CSS fixes / hacks here that might help. I've still be unable to reproduce on my end, but if we're able to reproduce any circumstance where a horizontal scrollbar appears, the jumpiness maay go away if we ensure there's never a horizontal scroll (though in my testing across multiple browsers on my machine, I've been unable to get a horizontal scroll).

**Comment by LukeCaley** [comment] 2020-09-09 17:20
As discussed on the call today (09/09), if this is confirmed as a specific browser issue then fine to accept as a known issue that _should_ be resolved with chrome updates.  Before doing this, great if @imohkay could investigate and note details here as per 

> @imohkay - this maybe worth looking at to see if there's any CSS fixes / hacks here that might help. I've still be unable to reproduce on my end, but if we're able to reproduce any circumstance where a horizontal scrollbar appears, the jumpiness maay go away if we ensure there's never a horizontal scroll (though in my testing across multiple browsers on my machine, I've been unable to get a horizontal scroll).

**Comment by imohkay** [comment] 2020-09-10 06:10
@frozenhelium @LukeCaley @batpad I took a look and it appears to be the CSS Transforms (inserted into the DOM and dynamically updated via JS) via the [react-tether plugin](https://github.com/danreeves/react-tether).
Fixing this won't be too straightforward, IMHO.

This react-tether plugin is used within the dropdown plugin to accurately position the dropdown content below the dropdown header via JS (e.g. the dropdowns in the global navigation).

If we remove the tether plugin, we will have to manage that ourselves in the dropdown plugin.

Chrome on Windows is where I tested. I also tested on FF and Edge browsers on Windows, and there is no scrollbar on these browsers.

**Comment by frozenhelium** [comment] 2020-09-11 10:04
[This PR](https://github.com/IFRCGo/go-frontend/pull/1565) fixes this issue by replacing all dropdowns that use react-tether plugin. There's still some stylings to be fixed. After discussing with @batpad we decided to merge this to test it out properly and fix the styling later.

The drop downs were replaced in following places and might need some styling touchup:
* `components/mobile-header.js`
* `components/common/filters/date-filter-header.js`
* `components/header.js`
* `components/display-table.js`
* `components/header-region-button.js`
* `components/connected/user-menu.js` (definitely needs styling fix)

CC: @imohkay

**Comment by batpad** [comment] 2020-09-11 10:10
Re-opening since it seems to have been accidentally closed via commit message.

**Comment by batpad** [comment] 2020-09-11 10:11
It would be great to test if this seems to have fixed the issue.

@LukeCaley @nanometrenat would you be able to test staging and see if the jump on scroll for RTL is now gone?

@imohkay am co-assigning you here. Will be great if you can take a look at the styling touch-ups that are needed with the new dropdowns.

**Comment by nanometrenat** [comment] 2020-09-11 10:45
@batpad Just checked in staging and I'm afraid it's still flicking round for me.

**Comment by frozenhelium** [comment] 2020-09-11 10:57
@nanometrenat the build failed and that fix didn't make it up to the staging. It's there now.

**Comment by nanometrenat** [comment] 2020-09-11 11:09
It scrolls BEAUTIFULLY now!  thanks team

**Closed** 2020-09-14 05:31 UTC

**Comment by batpad** [comment] 2020-09-14 08:30
Closed accidentally due to commit message, re-opening.

The fix for this involved changing the way we handle the Dropdown component in the header - used for the Field Report Dropdown and language selector.

@karitotp - could you please test that the dropdowns in the header continue to work correctly? 

@LukeCaley since we have had a hard time reproducing the bug on non-Windows machines, it would be great if you were able to confirm that the janky scroll behaviour is now gone on staging.

**Comment by karitotp** [comment] 2020-09-14 14:39
> @karitotp - could you please test that the dropdowns in the header continue to work correctly?

@batpad, they work good to me
