### ISSUE TITLE
Separate national societies from countries

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-frontend#475] opened 2018-10-10 21:37 UTC
For future work:

Currently, the national society is a property of the country model. I think it makes sense to create a wholly separate table from societies or Red Cross groups that has a foreign key to countries. For example, IFRC deploys staff, but it doesn't make sense to call it a country.

cc #467

**Comment by szabozoltan69** [comment] 2018-11-08 10:57
What do you suggest, Derek, shall I change the recent country model-structure ( = remove society_name and society_url from it), or let's just define a new model for "irregular" societies (rc_group) while we leave the recent country model untouched?

**Comment by dereklieu** [comment] 2018-11-08 15:39
I think it makes sense to separate them (the first option) as they do seem different, ie a country can have 0, 1, or multiple societies associated with it, and furthermore a society might be associated with 0, 1, or multiple countries.

This will complicate the queries some.

Overall I'd recommend stepping back and taking stock of the current issues that lead to this recommendation, and making sure they are still valid and that this is still the best way to solve those issues. cc @mmusori @LukeCaley @guipizzini

**Comment by szabozoltan69** [comment] 2018-11-08 15:50
Thank you Derek. (I also have some fear about the caused _complicated queries_; it can be similar to the effect of "richer CSV" request, which (after the implementation) caused 10-12 other frontend issues which were not easy to detect and fix.)

**Comment by ElsaRaunioIFRC** [comment] 2018-11-29 08:46
@szabozoltan69 Is there anything else to work on this issue? If everything is finished, I'll close the issue.

**Comment by szabozoltan69** [comment] 2018-11-29 08:50
@ElsaRaunioIFRC Well, the restructuring did not happen until now, but we can return to this, if someone else also needs this. It was just an idea, but the implementation is a bit risky (for me). We can close it.

**Closed** 2018-11-29 08:50 UTC
