### ISSUE TITLE
[PROD] Country error in map

### ISSUE THREAD

**Issue by GregoryHorvath** [IFRCGo/go-frontend#991] opened 2020-03-09 12:01 UTC
## Issue

> Kindly  concerns are being raised about Central Africa  Republic Map on go platform,  Information about CAR appears to be labelled under Cameroon. The information is misleading.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/30079559/76211066-ae7ce280-6205-11ea-94a4-e9ff8a2f6012.png)

## Related feature
MSM ticket - SRV-18274

**Comment by nanometrenat** [comment] 2020-03-09 14:50
@GregoryHorvath note that the Cameroon office is the location of the Central Africa Country Cluster office - so if an appeal is for the Central Africa CCST (rather than for one specific country) it is correct for it to show as Cameroon.  However if the appeal is for the COUNTRY Central African Republic then it should show as CAR.
@LukeCaley FYI

**Comment by GregoryHorvath** [comment] 2020-03-10 08:23
> @GregoryHorvath note that the Cameroon office is the location of the Central Africa Country Cluster office - so if an appeal is for the Central Africa CCST (rather than for one specific country) it is correct for it to show as Cameroon. However if the appeal is for the COUNTRY Central African Republic then it should show as CAR.
> @LukeCaley FYI

@nanometrenat I've found out the Country is set to Cameroon for the Floods Appeals. I've passed the MSM ticket about it to you in case this is an issue with just setting the Country to Central African Republic for the Appeals. If not then sorry for the ticket-volleyball, then what should the correct behaviour be for this?
@batpad FYI

**Comment by nanometrenat** [comment] 2020-03-10 11:19
Hi, I updated the ticket SRV-18274 - basically it's because this data is coming through that way on the Appeals ingest - so that is where you will need to investigate!  Thanks.

**Comment by GregoryHorvath** [comment] 2020-03-11 08:59
Hi @nanometrenat, so I found this part: https://github.com/IFRCGo/go-api/blob/b8404016e125c8c898b147fb515717198045ae51/api/management/commands/ingest_appeals.py#L19

Where it ingests the appeals from: http://go-api.ifrc.org/api/appeals, and if `<GEC_code>CAF</GEC_code>` (which I assume is a region code) then the country is defaulted to Cameroon based on the above mapping.

We have these fields in the XML which we could use for a solution:
`<GEC_code>CAR</GEC_code>`
`<OSC_name>Cuba, Haiti and Dominican Republic country cluster</OSC_name>`
`<OSR_name>Americas</OSR_name>`
`<OSS_name>Cuba, Haiti and Dominican Republic country cluster</OSS_name>`

`<OSC_name>` is used as a `country_name` but only in a case if it can't find the `iso_code` mapping (above): https://github.com/IFRCGo/go-api/blob/b8404016e125c8c898b147fb515717198045ae51/api/management/commands/ingest_appeals.py#L145

Should I just change `CM` to `CF` (Central African Republic) when the `<GEC_code>` is `CAF` or what would be the best approach here?

**Comment by nanometrenat** [comment] 2020-03-11 12:25
Hi, we definitely want Cameroon to remain affiliated to Central Africa Country Cluster.  So it is correct that if it comes through as CAF then it should be mapped to cm.

The question is why it is coming through as CAF - because @teklal and @mmusori have apparently checked the underlying data in the Data Warehouse and I am told it is correctly mapped there.

- do you have access to any documentation re where precisely go-api.ifrc.org pulls its data from?
- are you able to please send through (via email or teams) the full extract of the xml response to the API call for this appeal (or ideally for all current appeals)?  Presumably the extract of xml you have above is not from the current appeal we're talking about as it's a different continent ;)

Thanks a lot
@LukeCaley fyi

**Comment by nanometrenat** [comment] 2020-03-11 17:52
Thanks for sharing info @GregoryHorvath 
Confirmed that the appeal data coming through isn't what is expected.  Checking with IFRC Finance.

**Comment by teklal** [comment] 2020-03-11 18:38
Double-checked the information on BO and Apple and the appeal really is linked to CAR there.

Just noticed something interesting: on GO looking at "All Emergencies for Cameroon" https://go.ifrc.org/appeals/all/?country=41 I notice that this seems to have been a problem on a lot of prior occasions as well

And the same section for CAR: https://go.ifrc.org/appeals/all/?country=44 
It seems that ever since GO was launched none of the appeals for CAR have linked to CAR but have been linked to Cameroon instead. 

So this is not just a one-off situation for this particular appeal but there seems to be a problem in the mapping.

**Comment by nanometrenat** [comment] 2020-03-13 17:14
Contrary to Tekla's comment above, the information on BO and APPLE was actually **INcorrect**  It was a source data issue rather than a GO issue.

Looking at MDRCF025 it was showing in APPLE as Geographical Code CAF (which is the code for Central Africa, in IFRC ) rather than Geographical Code CF (which is the iso-2 country code for the country Central African Republic). 

Finance have amended this appeal (and the others that were similarly mis-mapped) on APPLE and it has now fed through to GO via the automatic appeals ingest.

Closing this issue, thanks a lot

**Closed by nanometrenat** 2020-03-13 17:14 UTC
