### ISSUE TITLE
Key Numbers - styling across the platform

### ISSUE THREAD

**Issue by mariam-yu** [IFRCGo/go-frontend#1324] opened 2020-06-10 10:01 UTC
UI styling for the top key numbers across the platform. The UI proposal should be upon acceptance be implemented by the front-end team.

**Comment by maisa-yu** [comment] 2020-06-24 13:01
Key Numbers Modules on pages:
1.0_GO_Home
2.3_GO_Regions_3W
3.2.1_GO_Country_3W
4.1_GO_Emergencies
4.2.1_GO_Specific-Emergency

**Comment by imohkay** [comment] 2020-06-26 09:08
@maisa-yu @mariam-yu For small UI questions, should I ping both of you or just Maisa? I wanted to check what the base body font color of the site is. Does it remain #000000 (the current color)?

**Comment by maisa-yu** [comment] 2020-06-26 09:51
> @maisa-yu @mariam-yu For small UI questions, should I ping both of you or just Maisa? I wanted to check what the base body font color of the site is. Does it remain #000000 (the current color)?

@imohkay you can ping me on UI questions. And yes, the base body will remain #000000

**Comment by imohkay** [comment] 2020-06-26 10:12
@maisa-yu Thank you:)

**Comment by imohkay** [comment] 2020-06-26 10:43
@maisa-yu Also, for the Key Numbers on the main Emergency page, is this what we want to change? _(See attached file)_
If the screenshot below is correct, do I also change the SVG icons to match the red color of the other key numbers on different pages?
[
![emergency-key-numbers](https://user-images.githubusercontent.com/1667470/85849001-c9c92900-b7c7-11ea-867d-f4f8754a8ef3.png)
](url)
Also, I'm unsure what needs to be changed for this point: 4.2.1_GO_Specific-Emergency
Could you please point me to a specific example on the site? Thanks.

**Comment by imohkay** [comment] 2020-06-26 10:54
@maisa-yu one more question: On the homepage, should I move the key numbers up (above the Highlighted Operations section) to match the Zeplin file?

**Comment by maisa-yu** [comment] 2020-06-26 11:09
@imohkay for **Key Numbers on the main Emergency page** yes, the screenshot you sent will be replaced by the new version as per zeplin, let me know if you have any issues getting the svg icons there. 

This page: **4.2.1_GO_Specific-Emergency** will be in the same format but we still don't have the full page done, we're working on that. 

For **Homepage** yes, the key numbers will be higher up.

**Comment by imohkay** [comment] 2020-06-26 11:15
@maisa-yu Thanks! I'll wait for the Specific Emergency designs to come in, and work on the key numbers on the other pages in the meantime.

**Comment by imohkay** [comment] 2020-06-27 08:33
@maisa-yu Hey... you can take a look here: https://ifrc-go-feature-1324-key-nos-ui.surge.sh/
Could you let me know if the styling's okay? Home, Country/Region and Landing page of Emergency have been done.

**Comment by maisa-yu** [comment] 2020-06-29 14:42
@imohkay Thanks for that! So I'm only commenting on key numbers and titles for now. 

The cards are good in styling, but could you check the (i) icons? some cards don't have it. 

On **Home** could you check the letter spacing of the title? Also, can you make the width of the subtitle as per zeplin? (so it doesn't go all the width of the title) 

For **Regions**, the width of the cards seem to go way over the alignment, could you check that on zeplin? (In Home-staging the alignment is correct)
And the Title should be center aligned. 

We are working on **Emergency** pages, they'll change quite bit from what is now. There's one on zeplin so you can check, but as there will be some changes, you can wait to change all of that. 

Thanks!

**Comment by imohkay** [comment] 2020-06-30 06:35
@maisa-yu Thanks for the feedback: Wanted to check a couple of things:
1. Do we want this extra letter spacing only for the home page title? Or it needs to show up for all page titles?
2. Regions: Many of the pages appear to have a wider width than the home page. Should all of them be the same width as the home page? (I'm guessing so). That will fix the width of the cards.
3. Should all page titles be centred?
4. For the (i) icons, some of those cards don't have any info associated with them, hence they lack the icon. We could add the icons if there is information associated with the card.

**Comment by maisa-yu** [comment] 2020-06-30 10:32
Hi @imohkay 
1. All the page titles will have extra letter spacing, would that be an issue in any of the pages?
2. Normally all the pages have the same width, are they showing differently on zeplin or elsewhere?
3. Yes, they're all centered, if there's an exception we'll add on zeplin, but so far everything is centered. 
4. Maybe there was a mistake in the cards, but they should all have the icons, I'll check that again. 
Thanks!

**Comment by imohkay** [comment] 2020-06-30 10:42
@maisa-yu Thanks. The reason I was checking about the global styles is that many of the pages on the current site don't have the consistency of styles, so I'll make the changes accordingly in one page (w.r.t. to page widths, centered titles, letter spacing, etc.) We can also check with Luke about the info icons. Thank you. I'll update the links in a few hours once I'm done :)

**Comment by maisa-yu** [comment] 2020-06-30 11:30
@imohkay Ah, you're right, I missed the icons... It is true that they're only on the first 2 cards, you can leave it like that. 
And yes, we're slowly trying to make it more consistent :) it'll probably be easier to see once we complete all the pages.

**Comment by imohkay** [comment] 2020-06-30 17:27
@maisa-yu Updated the link: https://ifrc-go-feature-1324-key-nos-ui.surge.sh
All titles across the site have the new letter spacing and are centered, and I've ensured the widths of all the pages are the same, which should hopefully fix the different widths for the key number sections.

**Comment by imohkay** [comment] 2020-07-04 07:55
@karitotp Hi :) Could you take a look at the Zeplin design here? https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b
The key numbers across the site are supposed to match the new Zeplin designs.
I have also center-aligned the top page titles and tried to ensure all the pages on the site have the same width.
If you see any issues with center alignment for headings and anything else, do let me know. Thank you :)

**Comment by karitotp** [comment] 2020-07-06 13:39
Hi @imohkay, I do not have access to https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b, could someone give me access or send me an invite please.

**Comment by maisa-yu** [comment] 2020-07-06 14:07
Hi @karitotp I can give you access, could you give me the email you wish to sign in with?

**Comment by karitotp** [comment] 2020-07-06 14:17
:wave: @maisa-yu, to this email `karito@developmentseed.org` please. Thanks!

**Comment by maisa-yu** [comment] 2020-07-06 14:19
@karitotp should work now :)

**Comment by karitotp** [comment] 2020-07-06 14:56
:wave: @imohkay, In general all the titles looks good and the key numbers style match with the design in zeplin :+1: 

> I have also moved the first 3 sections around, based on the Zeplin design for the home page.

If this refer to the HIGHLIGHTED OPERATIONS section, this was moved to the last part of the page but seeing in the zeplin design this is still in the first part https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b

**Comment by karitotp** [comment] 2020-07-06 14:57
:wave: @imohkay, In general all the titles looks good and the key numbers style match with the design in zeplin :+1: 

> I have also moved the first 3 sections around, based on the Zeplin design for the home page.

If this refer to the HIGHLIGHTED OPERATIONS section, this was moved to the last part of the page but seeing in the zeplin design this is still in the first part https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b

**Comment by imohkay** [comment] 2020-07-07 06:26
@karitotp Thanks :)
Should we close this ticket?

**Comment by imohkay** [comment] 2020-07-07 06:47
@karitotp Sorry, I was just informed that tickets are only closed after prod is updated.... Ignore the above comment...

**Comment by imohkay** [comment] 2020-07-07 14:33
@karitotp are we okay with the ordering of things on this page (I mean moving the key numbers up)? I believe this is what the design indicates and was confirmed by the design team.

**Comment by karitotp** [comment] 2020-07-07 15:56
Hi @imohkay, I am just comparing with the design here https://app.zeplin.io/project/5c9244a648d5c424ccf27cfb/screen/5ebd38896a3c2230f204bd5b and the home page in https://ifrc-go-feature-1324-key-nos-ui.surge.sh/ and I see that the section :point_down: is in different order.
![Screenshot from 2020-07-07 10-46-29](https://user-images.githubusercontent.com/11504548/86807164-3bfb0280-c03f-11ea-815f-b30595b15822.png)

I do not sure which one is the correct, please confirm that with the design team :pray:

**Comment by imohkay** [comment] 2020-07-07 16:27
@maisa-yu Hey, quick question. On the homepage, do we want highlighted operations just below the key numbers? As the second section on the page?

**Comment by maisa-yu** [comment] 2020-07-07 21:26
Hi @imohkay yes, the version on zeplin is correct, we're moving Highlighted operations just below Key numbers.

**Comment by imohkay** [comment] 2020-07-10 11:45
@maisa-yu Hey, a couple of questions about main page headings since we discussed that here.
1. Now that headings are centered across the site, what happens to pages like Country, which have buttons near the header?
Are those moved below the header and centered?

**Comment by maisa-yu** [comment] 2020-07-10 16:37
@imohkay You can see an example on Country 3W, it'll be centred across the site.

**Comment by imohkay** [comment] 2020-07-10 18:01
@maisa-yu sounds good. Thank you :)

**Comment by nanometrenat** [comment] 2020-07-16 11:31
Hi, just chanced across a place in Staging where the key figs look weird to my eyes - see screenshot.  This is the staging version of the Global COVID-19 appeal page so this one defo needs to look fab!  Might still be a work in progress but just letting you know: https://dsgoproxyapp.azurewebsites.net/emergencies/3983#details
Cheers

![image](https://user-images.githubusercontent.com/33625192/87666193-757eec80-c768-11ea-97f0-4d79ec874a8a.png)

**Comment by karitotp** [comment] 2020-07-17 14:41
As Natalie mention, there are other things that looks weird too:
- Dropdowns and details in popup of the map aligned to right, and like this, stat in charts, countries in the region page are aligned to the right too.
Here some screenshots:

![Screenshot from 2020-07-17 09-25-37](https://user-images.githubusercontent.com/11504548/87796959-b2ea8500-c80f-11ea-9132-560cbeed83bd.png)

![Selection_016](https://user-images.githubusercontent.com/11504548/87797804-d3670f00-c810-11ea-8496-a188b210dc1c.png)

![Screenshot from 2020-07-17 09-39-20](https://user-images.githubusercontent.com/11504548/87798301-71f37000-c811-11ea-839d-b997411f3b35.png)

**Comment by LukeCaley** [comment] 2020-08-04 13:30
@batpad can you confirm that this ticket and issues which have been subsequently identified by @karitotp have been fixed and tested?

**Comment by karitotp** [comment] 2020-08-04 17:51
Currently none of the issues mentioned above are on the staging site.

**Comment by guipizzini** [comment] 2020-08-06 08:43
this looks good, and all fixed. working correctly after testing.

**Comment by nanometrenat** [comment] 2020-08-07 14:54
Accepting risk, going to Production now

**Closed** 2020-08-10 20:40 UTC
Labels: UI - Design
