### ISSUE TITLE
Case sensitive username

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#471] opened 2018-10-03 15:06 UTC
## Issue

*The system is strict with case-sensitive characters.*

## Steps to reproduce

*If a user registers their account as for example **TestUserAccountName** then if they try to login doing **testuseraccountname** they are not able to login*

## Expected behavior

*we would like to have the ability that if a user tries to use an upper case character the system automatically sets it as lower case and that they can login whether they've inserted upper or lower case in their login. The password should remain case sensitive*

**Comment by szabozoltan69** [comment] 2018-10-03 15:29
This raises some further questions; mainly concerning the already existing usernames, where the username is case sensitive.
For example, there is **adesh** and **Adesh**, and these two means two different users.

If I put a conversion into the program, that "always make lowercase from the user's input", then Adesh will not be able to log in.

(Maybe a solution can be: making lowercase usernames for the future registrations in registrate time, but this does not mean anything the already existing users – for them the system should work as it is now. Or: let's change usernames for the cases where the case sensitivity matters.)

**Comment by szabozoltan69** [comment] 2018-10-04 13:32
I made a correspondance with the 5 users, they told me which username (and so: password) will they use in the future, and the other login names was set to is_active = false (by me in production database). Now I wait for a review and PR for the case_insensitive_username branch.

**Comment by dereklieu** [comment] 2018-10-10 21:33
@szabozoltan69 @guipizzini please close this is the issue is addressed.

**Comment by szabozoltan69** [comment] 2018-10-11 06:51
Ok, it's solved.

**Closed by szabozoltan69** 2018-10-11 06:51 UTC
Labels: Must Fix
