### ISSUE TITLE
[PROD] Field Report view - not all fields are displayed 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-frontend#1932] opened 2021-06-10 07:09 UTC
## Issue
*Description (Health) field is not displayed on the field report view, however the data is available in the database. Not sure, if this is the case at other fileds as well. This occurs only on PROD, STAG works fine.*

PROD:

FIeld report view:
https://go.ifrc.org/reports/14370
![image](https://user-images.githubusercontent.com/68283148/121480362-477f4800-c9cb-11eb-97cb-05181d098a73.png)

Admin page:
https://goadmin.ifrc.org/en/api/fieldreport/14370/change/
![image](https://user-images.githubusercontent.com/68283148/121480500-6f6eab80-c9cb-11eb-9dc2-7714e1987bd5.png)

STAG:

Field report view:
https://dsgoproxyapp.azurewebsites.net/reports/9776
![image](https://user-images.githubusercontent.com/68283148/121479884-ca53d300-c9ca-11eb-80ce-c97a4ec7ccad.png)

Admin page:
https://dsgocdnapi.azureedge.net/en/api/fieldreport/9776/change/
![image](https://user-images.githubusercontent.com/68283148/121479767-a7c1ba00-c9ca-11eb-89e1-d5b17e0100e6.png)

**Comment by frozenhelium** [comment] 2021-06-14 10:37
@tovari
@batpad and I figured out that, at least one of the action fields need to be checked for the notes to be displayed. In the screenshots above, for staging server, under the *Actions taken by National Society*, `Risk communication, community engagement, and health and hygiene promotion` and `Ambulance services for COVID-19 cases` are checked as actions, so the note appear there. But in the production, we do not have any actions checked, so the note doesn't appear there. This is the currently implemented logic.

Let us know if we should change this logic.

**Comment by batpad** [comment] 2021-06-15 06:58
@frozenhelium - I spoke to @mmusori and confirmed the desired behaviour here:

Users should only be able to fill in the `notes` text field if they have selected AT LEAST ONE action from the checkboxes. So, on the view field report page, what we are doing currently is correct: we do not want to show the notes if there is not at least one action selected. The logic here being is that the notes are supposed to be additional notes for the Actions you have selected, so if there are no Actions selected, adding notes does not make sense. There exists an `Other` action that users should select if their Actions don't fit neatly into one of the existing categories.

So, the fix here would be to add some validation to the field report form to not allow a user to add notes if there is not a single action checkbox for that section selected: i.e. if the notes text field is non-empty, check that at least one Action is selected, else, show a validation error.

@frozenhelium let me know if that makes sense.

@tovari - to be clear here, this is not a new issue / caused due to the field report refactor - it seems just unlucky coincidence that we had someone submit a field report with notes but no actions selected at this time when we were dealing with existing issues (and landed up making finding the root cause a bit harder with multiple issues at hand).

My suggestion for next steps here would be:

 - Add this validation step as a feature / enhancement to the field report. I would not try and hotfix this, but let it go through our normal testing + release process. @frozenhelium do you think this is realistic to aim for for release toward end of this month?

- For the submitted field report(s) on prod that have this issue, just edit the form to add at least one Action to the relevant sections with Notes. @mmusori suggested to use the `Other` Action in case it is not clear which Action to check.

**Comment by frozenhelium** [comment] 2021-06-15 07:04
@batpad yep, we'll be able to complete this one in this sprint

**Comment by batpad** [comment] 2021-07-08 05:55
@frozenhelium sorry, did we ever add the validation fixes here?

**Comment by frozenhelium** [comment] 2021-07-09 13:19
@batpad we haven't add the validations yet

**Closed** 2024-02-26 10:33 UTC
Labels: DFS
