### ISSUE TITLE
User Profile in Django

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#403] opened 2018-08-07 09:07 UTC
## Issue

Users that have all the necessary "assigned" actions cannot see the list of alerts they've submitted and cannot assign the alert to an "event" (emergency in the front end?).

They can do this if we assign them the "change event/create event" role which we do not want this to happen.

**Comment by dereklieu** [comment] 2018-08-07 17:42
If a user assigns an alert to an emergency, they are also creating a link from the emergency to the alert, and there's not much we can do about this. They don't need to be able to create new events, just modify.

**Comment by guipizzini** [comment] 2018-08-07 19:45
Totally in agreement. But the dropdown of ‘event’ (which should be emergency in order to be consistent throughout the application) is not available. When users go and select the emergency related to the alert the dropdown is not giving results...

**Comment by dereklieu** [comment] 2018-08-07 20:14
I believe these users would require permissions to both edit events, and also edit events that belong to a specific country or region. So if they can edit any events, you could give them editor permissions for all five regions.

**Comment by dereklieu** [comment] 2018-08-22 20:39
@guipizzini I looked into this more and, as far as I can tell, there's no way to allow users to assign alerts to emergencies without also giving them the ability to also edit emergencies.

**Comment by LukeCaley** [comment] 2018-08-23 11:32
We need to consider carefully in relation to user roles and profiles.  Seems there would be quite a big risk of user error to open up too many permissions.  TBD @guipizzini

**Comment by ElsaRaunioIFRC** [comment] 2018-11-29 09:38
@szabozoltan69 User rights are among our key priorities right now. Our idea is to have a set of pre-assigned rights according to the user's function, region and operation. However, as we observed with the user Manoj Khadka, grouped user rights do not seem to work yet as planned. Currently, we have been assigning the rights individually which is very time-consuming and prone to errors.

**Comment by szabozoltan69** [comment] 2018-11-29 09:51
@ElsaRaunioIFRC User and group rights setting is a parametering issue, does not need developer intervention. If something does not work as we would like to, then of course, the reason and root cause should be found. The Django "group" entity gives possibility to define sets of permissions. We can begin to explore it better.

**Comment by teklal** [comment] 2020-01-10 14:02
Closing as user rights and permissions(and the way we do them) are currently reviewed by @nanometrenat

**Closed by teklal** 2020-01-10 14:02 UTC
Labels: Must Fix
