### ISSUE TITLE
3w: Unify user roles to match rest of Go

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1312] opened 2020-06-03 13:13 UTC
Go 3w has three visibility levels: Public, Logged in User and IFRC only. This is not how Go treats users (and visibility) in general. The logic of how IFRC users are identified and the name of that visibility level should be adjusted to match the rest of Go.
@nanometrenat could you make sure this is correct and identify the desired nomenclature and function? Thanks!

**Comment by nanometrenat** [comment] 2020-06-04 17:36
To confirm, in rest of site the 3 visibility levels mentioned in dropdowns etc. are:

- Public (3) - not logged in
- Membership (1)
- IFRC (2) - based on user group (or being a superuser)

The comment in this ticket has more detail re specifics:  https://github.com/IFRCGo/go-api/pull/748#issuecomment-634512962 and a link to a visibility class

Thanks!

**Comment by thenav56** [comment] 2020-06-17 10:24
@lauripynnonen @nanometrenat Thank you guys for the issue.

I also encountered this when doing translation work. I have already fixed this but will take some time to push the changes.
But the changes will not impact any data on the **go-api**, will only change the visible text.

**Comment by nanometrenat** [comment] 2020-08-11 15:42
@LukeCaley moving back to 4.3 as actually it looks like changes have been merged for this so it is going through the process already.
@thenav56 can you please confirm what status this ticket should be - is it Ready for QA?

**Comment by thenav56** [comment] 2020-08-12 03:37
@nanometrenat It should be already in production. Nomenclature fix was pushed along the Django static translation PR. 

But the logic behind the usages of this roles seems to be different.
Basically, for 3W this logic https://github.com/IFRCGo/go-frontend/issues/1067#issuecomment-611374753 (email ending with @ifrc.org are **IFRC user**) is used to filter the projects. But for other entities, the logic seems to be a bit different where permission `api | country | IFRC Admin` is assigned from the admin panel to users manually stating the user is **IFRC user**.
Could you let us know which approach is suitable?

**Comment by nanometrenat** [comment] 2020-08-12 07:53
Hi @thenav56 it is great that the nomenclature has been changed.

The actual logic still needs to be changed - user permissions should not run directly off email address but rather off user groups.  IFRC Admin permission isn't assigned manually from admin panel, rather it is assigned via an automatic job.

However that piece of work can wait until 4.4 as per comment above.  Thanks a lot

**Comment by thenav56** [comment] 2020-08-12 08:16
Hi @nanometrenat Thanks for the clarification.

**Comment by nanometrenat** [comment] 2020-08-13 08:45
Hi @thenav56 further clarification - the nomenclature hasn't actually been changed in Production - see screenshot as at right now.  Nomenclature change is not in Staging either - still says "Logged in User".

@batpad seems there is some confusion about where these changes have been made - are you able to advise?  Thanks a lot

![image](https://user-images.githubusercontent.com/33625192/90113710-0a6a0b00-dd52-11ea-8fe1-5d5957d77fa2.png)

**Comment by thenav56** [comment] 2020-08-13 15:16
Hi @nanometrenat the nomenclature was fixed from the go-api (Admin Panel) perspective. Thanks for letting us know the issue is still present. This should be an easy fix. cc: @frozenhelium
Also, we are trying to pull all this information from backend in the go-frontend, so in the future, the static choices will have a single source avoiding confusion like this.

**Comment by thenav56** [comment] 2021-05-07 10:04
Updated visibility logic and nomenclature for projects according to the [comment](https://github.com/IFRCGo/go-frontend/issues/1312#issuecomment-672704352). The update is deployed to staging.

**Closed** 2021-06-04 10:17 UTC
Labels: 4 Hours, DFS, Maintenance
