### ISSUE TITLE
[Staging] Register screen stuck on loading

### ISSUE THREAD

**Issue by jhenshall** [IFRCGo/go-frontend#1541] opened 2020-08-27 15:47 UTC
## Issue
Register page on staging site gets stuck on loading and displays grey screen. In console, says `GET_COUNTRIES_FAILED` so could be linked to geo api changes? 

## URL
https://dsgoproxyapp.azurewebsites.net/register

## Steps to reproduce
Visit URL above.

## Expected behaviour
Page loads.

## Related feature
Possibly the geo api changes #1534 ?

**Comment by nanometrenat** [comment] 2020-08-31 08:36
@GregoryHorvath this wasn't on the board so I added it to 4.3 so people know where it's at.  Can you please put it to Ready for QA when it's ready?  thanks

**Comment by batpad** [comment] 2020-09-11 09:48
This should now be fixed in staging. Can you please confirm @jhenshall ?

cc @karitotp

**Comment by jhenshall** [comment] 2020-09-11 11:00
Thanks! The grey screen issue seems fixed but in trying to create a new account, the country field fails with 'should be string'. Is this a separate issue? Maybe related to the geo work?
cc. @batpad @geohacker @karitotp 

![image](https://user-images.githubusercontent.com/6359748/92917012-fa634b00-f425-11ea-9ea3-12980a87e25c.png)

**Comment by batpad** [comment] 2020-09-11 11:05
Thanks @jhenshall !

@geohacker do you know what might be the cause of this validation error? Something about the "type" of the country id and that needing to be updated in the validation schema?

cc @GregoryHorvath

**Comment by geohacker** [comment] 2020-09-11 11:26
Ah yes, this is a validation issue. I'll fix! Thanks for catching @jhenshall!

**Comment by batpad** [comment] 2020-09-14 08:12
The validation issue should now be fixed in staging.

@jhenshall could you please test and confirm?

@karitotp Would also be good to give a full test to the Register page functionality after this fix. Thank you!

**Comment by jhenshall** [comment] 2020-09-14 09:08
Thanks @batpad - successfully signed up as new user, so all good.

**Comment by karitotp** [comment] 2020-09-14 14:23
@batpad, in terms of mandatory fields, seems is not working good for the City an the Organization name when National society is selected, or could be that only there is missing the validation message

![Selection_051](https://user-images.githubusercontent.com/11504548/93097938-d4c78300-f66b-11ea-9a66-ca3d8c12dfe9.png)

**Comment by batpad** [comment] 2020-09-14 14:38
@karitotp yea, i think here the problem is that it only shows the first validation error and not all when submitting. We can track this as a separate issue if needed, cc @GregoryHorvath . thank you!

**Comment by jhenshall** [comment] 2020-09-15 13:35
@batpad @geohacker - not sure if this is related to this ticket but the country drop down on [staging register page](https://dsgoproxyapp.azurewebsites.net/register) now has 'no results found'. Also noticed some weird behaviour of the field report drop down not reflecting changes made in the database. Can create a new ticket if not related to this?

**Comment by batpad** [comment] 2020-09-15 14:15
> - not sure if this is related to this ticket but the country drop down on staging register page now has 'no results found'.

This seems to be a bug we have recently introduced. Looking to fix that right now.

> Also noticed some weird behaviour of the field report drop down not reflecting changes made in the database.

We now cache country names on the client side for up to a day. If you go to https://dsgoproxyapp.azurewebsites.net/clear-init-cache and reload, you should see latest changes from the db.

**Closed** 2020-09-23 11:46 UTC
