### ISSUE TITLE
Molnix/GO Integration

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-frontend#1638] opened 2020-10-05 10:41 UTC
**Is your feature request related to a problem? Please describe.**
The integration between the new Surge Database (Molnix) and GO is happening! In order to improve the accuracy, exhaustivity and real time publication in Go of the info related to RRM deployed positions and Alerts open positions for the IFRC operations. 

**Describe the solution you'd like**
An integration between the Molnix DB and GO that allow us to access the Alerts and deployed personnel accurately.

**Describe alternatives you've considered**
As of right now is being updated manually by the Surge team.

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Where does the data come from and how is it maintained?**
An operational tag using the GO id of the operation will be manually created in the Molnix DB whenever a deployment is needed on that specific operation. When an alert (open position in Molnix) is issued, Go will fetch this alert using the operational id as an identifier. As the recruiting process advances, GO will update the Alerts making it a deployed personnel if the recruitment process was succesful.

**Should there be any restrictions around viewing or updating information related to this feature**
Alerts should be public but deployed personnel only for members

**Links to documentation**
https://ifrcorg.sharepoint.com/sites/SurgeDB/Shared%20Documents/General/02%20-%20Execute%20(Implementation)/Integration/Go%20Surge%20Sign%20OFF.docx?web=1

https://ifrcorg.sharepoint.com/sites/GOIVfordeveloperteam/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x01200025FDB632BD36194688238A2A6BBE35F0&viewid=3100fc5d%2Df44b%2D45d0%2Da395%2De4eadb946720&id=%2Fsites%2FGOIVfordeveloperteam%2FShared%20Documents%2FGeneral%2FGO%20Surge%20RRM%20Molnix%20integration

**Comment by tovari** [comment] 2020-11-04 13:22
Child tickets:
alerts:
https://github.com/IFRCGo/go-frontend/issues/1659
deplyoments:
https://github.com/IFRCGo/go-frontend/issues/1664

**Comment by anamariaescobar** [comment] 2020-11-06 13:53
Mock up data has been added to bot Molnix and GO staging for both Alerts and deployments so @mariam-yu and @batpad can continue working. Please let me know if anything else is needed!

**Comment by anamariaescobar** [comment] 2020-12-08 15:20
@batpad Just copying Molnix email in here to keep track:

**Enable new alert modes (IFRC CR?)**

The use case is for I-Information / A-Alert / D-Deployment / S-Stand down messages. Each of these affect IFRC GO, with the timing on both platforms being of key importance. For this reason, the alert needs to be the triggering moment.
Typically each mode is targeted at the same recipients in related alerts (see [#[427]),](https://gitlab.molnix.com/users/sign_in) but not inherently, as they can theoretically be subsets or supersets combined of previous alert(s).
The difference really is about what happens with positions - everything else stays the same:
•	I - information only (could even be Simple alert if no information message is needed)
•	A - typically should open positions 
o	Set opens to now if opens > now, AND/OR
o	Set status to active if status != active
•	D - typically should make deployments visible 
o	Set deployment with related position to draft=false AND/OR hidden=false (DANGER: potential later rotation deployments with same parent position would also be affected), OR
o	Add new area to add deployments (like positions) to set draft=false AND/OR hidden=false
•	S - typically should close positions 
o	Set position to unfilled
The simplest and most dynamic way to approach this is actually not to implement any modes, but add selector for each position added to the alert with label "Action when alert is sent (new alert) or saved (when changing an existing alert)":
•	No action (default)
•	Ensure position is opened
•	Ensure position is marked unfilled
•	Ensure related deployment(s) are no longer hidden/draft
RPM would then be given a bit of intelligence on how to automate the hooks and alert response interface (for example, a position marked 'unfilled' will not show up).
Related: [#400](https://gitlab.molnix.com/users/sign_in) [#427](https://gitlab.molnix.com/users/sign_in) [#351](https://gitlab.molnix.com/users/sign_in)

**Comment by batpad** [comment] 2020-12-10 07:49
To summarize current development status and remaining actions, as discussed with @tovari and @anamariaescobar .

Backend `sync_molnix` script to sync data from Molnix is running on staging and generates logs that can be viewed in the admin. On the script, there is one change to be made based on the last conversation with the Molnix team:

 - When a position has been removed from Open Positions on the Molnix end, we need to make another request to Molnix for that position id to check whether the status is `unfilled` - if the status is `unfilled`, we keep the position as "is_active=True" on GO, but set the molnix_status to `unfilled`. On the frontend, we will then check for this status to show the position as a Stand-Down.

On the frontend, we will implement the new designs for all the things that are not dependent on new data fields coming in from Molnix. This means:

 - Showing Surge Alert table on emergency page
 - Implementing redesign with bar graph, etc. for deployments table on emergency page
 - Implement deployments table on Deployments page to group by Emergency
 - Implement All Deployments table to not show bar graph, etc. that shows on the deployments table on the emergency page.

 A lot of the frontend work for the implementations above has been done, so it will be finishing up these sections. What we will not do for this release is the modifications to the Surge Alerts table as that includes a lot of fields from Molnix that we will not have.

Once we are done with work on this release, we can create a separate branch for the surge alerts table modification to test on staging.

**Comment by tovari** [comment] 2020-12-15 09:02
The list of issue items found in the UAT:

- [ ] Tab and   tittle should cahnge from Deployments to Surge
![image](https://user-images.githubusercontent.com/68283148/102192533-31307d80-3ebb-11eb-95d4-d80292fa85b2.png)

- [ ] Key figures should not include Deployment HeOps anymore but include number of NS providing Rapid Response Personnel
![image](https://user-images.githubusercontent.com/68283148/102192590-44434d80-3ebb-11eb-805f-9d652def81c5.png)

- [ ] Style of Map incorrect, Rapid response personnel not showing in the map
![image](https://user-images.githubusercontent.com/68283148/102192684-6210b280-3ebb-11eb-9d0b-5c6116e94a7b.png)

- [ ] This graphics should be reflecting Rapid Response personnel and not ERU, tittles wrong, styling should match the designs
![image](https://user-images.githubusercontent.com/68283148/102192757-7bb1fa00-3ebb-11eb-8d03-8f2b7057170f.png)

- [ ] Open Surge Alerts not showing

- [ ] Deployments   overview by operation should only show active deployments, I checked a couple   of deployments in the backend and most of them are not active anymore, also   maybe should we paginate this? I think is too long to show all the list
![image](https://user-images.githubusercontent.com/68283148/102192956-bddb3b80-3ebb-11eb-9969-72171859fc71.png)

- [ ] Rapid Response tab should be named Surge
![image](https://user-images.githubusercontent.com/68283148/102192996-cd5a8480-3ebb-11eb-8c7f-b3b8fa821e39.png)

- [ ] Key Figures not showing at all.
![image](https://user-images.githubusercontent.com/68283148/102193052-e19e8180-3ebb-11eb-89ab-31a8e2979733.png)

- [ ] Created a new Open Surge alert  with a closing date in the past, is still showing, need to be marked as not active in the backend in order to not be shown.

- [ ] Tittle should be Open Surge Alerts and not Opens Surge Positions
![image](https://user-images.githubusercontent.com/68283148/102193167-072b8b00-3ebc-11eb-9d74-16f2dbdaca9c.png)

- [ ] Tittle should be Rapid Response Personnel
![image](https://user-images.githubusercontent.com/68283148/102193222-1ca0b500-3ebc-11eb-9602-8493d2d409f7.png)

- [ ] Gant graphic is missing the line for today, the bars maybe should be gray as in the design?
![image](https://user-images.githubusercontent.com/68283148/102193266-2de9c180-3ebc-11eb-801d-f7537a2e1dda.png)

- [ ] Create a new ERU deployment, is appearing fine in the general deployments page but only appears in the emergency page if I click on the operation from the general deployments page, is I change the language or go to the emergency page without going through the general deployments page the ERU deployed section dissappears.

- [ ] "View all deployed Personnel and ERU" we should remove the ERU in this one as we are currently showing them ina different section
![image](https://user-images.githubusercontent.com/68283148/102193354-4a85f980-3ebc-11eb-8f46-a122d4bae4af.png)

- [ ] CSV Export of ERU deployed has to many columns and data is spread everywhere
![image](https://user-images.githubusercontent.com/68283148/102193418-5a9dd900-3ebc-11eb-8340-aef77f2887bc.png)

- [ ] All Deployed personnel is showing only the active deployments, should showw all of them
![image](https://user-images.githubusercontent.com/68283148/102193491-6d181280-3ebc-11eb-9436-adba4c48cda8.png)

- [ ] Csv export of all deployed personnel is including some kind on html text at the end
![image](https://user-images.githubusercontent.com/68283148/102193542-81f4a600-3ebc-11eb-8047-bffae77aef92.png)

- [ ] No option for view all open surge alerts

- [ ] No option for view all rapid response personnel deployed

- [ ] No option for view all eru deployed

**Comment by GregoryHorvath** [comment] 2020-12-15 10:33
> CSV Export of ERU deployed has to many columns and data is spread everywhere

As Django is pulling every relation by default, I can see that every field of the connected Emergency, its Field Reports, Appeals, etc are in there. We'd need a clear requirements of this CSV what to contain.

I also see that there are multiple `eru-owner eru-set` fields there, which I'm really confused about because only 1 `ERUOwner` can be connected to an `ERU` to my understanding. And of course we have every detail of those there too, which I believe are mostly unnecessary @batpad

**Comment by GregoryHorvath** [comment] 2020-12-15 10:59
> Csv export of all deployed personnel is including some kind on html text at the end

I'm not sure if I found exactly which was mentioned here, but we're definitely pulling the Emergencies' data here as well, which contains its `summary` which is a Rich Text field (could contain HTML). @batpad

**Comment by batpad** [comment] 2020-12-15 12:31
@anamariaescobar @tovari - I have put a checkmark on all the issues above which have been fixed and are ready to test on staging.

Based on discussions, we will ticket some of the other issues separately as they are existing issues on the site.

And the issues of new data-points to be displayed, we will tackle by the time the Molnix system is in production.

**Comment by batpad** [comment] 2020-12-15 14:41
> Gant graphic is missing the line for today, the bars maybe should be gray as in the design?

This should now be on staging.

**Comment by karitotp** [comment] 2021-01-07 21:23
> I have put a checkmark on all the issues above which have been fixed and are ready to test on staging.

   > - [x] Tittle should be Open Surge Alerts and not Opens Surge Positions

This is still as Open Surge Positions.

**Comment by GregoryHorvath** [comment] 2021-01-08 07:57
> > I have put a checkmark on all the issues above which have been fixed and are ready to test on staging.
> 
> > * [x]  Tittle should be Open Surge Alerts and not Opens Surge Positions
> 
> This is still as Open Surge Positions.

@karitotp Deployed a fix to staging.
cc @batpad

**Comment by batpad** [comment] 2021-01-08 09:03
Can we confirm the intended behaviour with @anamariaescobar ? @anamariaescobar can you check the changed table title from Open Surge Positions to Open Surge Alerts and say whether that's correct? I don't remember clearly if it is intentionally different from the mockups.

**Comment by anamariaescobar** [comment] 2021-01-12 09:10
Hi @batpad, sorry for the delay, after confirming with the Surge team, they want to go with Open Surge Alerts........positions will be used in the Molnix side, but since right now they are putting Stand downs, Information, Deployed messages etc, its better to leave it as Open Surge Alerts.

**Comment by anamariaescobar** [comment] 2021-06-11 08:01
List of matching NS from Molnix:

- [ ] Red Cross Society Of China-HongKong Branch --> Red Cross Society of China
- [ ] Macau Red Cross --> Red Cross Society of China
- [ ] IfrcHeadquarters --> IFRC
- [ ] IfrcMena --> IFRC
- [ ] IfrcAsiaPacific --> IFRC
- [ ] IfrcAfrica --> IFRC
- [ ] IfrcAmericas --> IFRC
- [ ] IfrcEurope --> IFRC
- [ ] IcrcStaff --> ICRC
- [ ] NotAffiliatedToMovementOrganization --> Blank

@batpad

**Comment by batpad** [comment] 2021-06-23 05:13
> Red Cross Society Of China-HongKong Branch

@anamariaescobar Can you tell me exactly how this is called on the Molnix side (with correct capitalization and spacing?)

**Comment by batpad** [comment] 2021-06-23 05:14
> IfrcMena --> IFRC

For these as well, could you tell me exactly how they come through from Molnix?

**Comment by anamariaescobar** [comment] 2021-06-23 07:22
Hi @batpad:
 Red Cross Society Of China-Hong Kong Branch                    
 Ifrc Headquarters                                              
 Ifrc Mena                                                     
 Ifrc Asia Pacific                                               
 Ifrc Africa                                                    
 Ifrc Americas                                                  
 Ifrc Europe                                                    

I have pasted exactly how they come from Molnix, it seems they all have a space at the beginning and enough spaces at the end that when you add up the characters and spaces adds up to 64.

**Closed** 2021-09-10 13:25 UTC
Labels: feature
