### ISSUE TITLE
[Staging] Edit Event functionality is available for edition when the user is not logged

### ISSUE THREAD

**Issue by karitotp** [IFRCGo/go-frontend#1482] opened 2020-07-30 15:22 UTC
## Issue
An specific emergency can be edited trough the Admin site even when the user is not logged.

## URL
Ex. https://dsgoproxyapp.azurewebsites.net/emergencies/4049#details

## Steps to reproduce
While you are not logged, go to an emergency https://dsgoproxyapp.azurewebsites.net/emergencies/4049#details and click in Edit Event button, the page redirect you to the Admin site where you can make editions

## Expected behavior
I assume that if the user is not logged the page have to redirect you to the login page, instead to the Admin site.

**Comment by batpad** [comment] 2020-07-31 08:58
@karitotp I think this is because you need to login to the frontend and backend separately. In this case, my hunch is, you were logged into the admin, even though you were logged out of the frontend, so then the Edit link would take you directly to the Edit Emergency page and not redirect you to Login.

If that makes sense, then that is expected behaviour. We maybe able to unify login at some point, but that would be a separate issue.

**Comment by karitotp** [comment] 2020-07-31 14:09
Yeah @batpad, you are right, that was because I was logged on admin site, if I am not logged the Edit event redirect me to the Admin logging.

**Comment by nanometrenat** [comment] 2020-08-04 21:46
Closing this ticket based on the above.  Correct behaviour for the button to direct user to the Admin site, correct behaviour for the user to be asked to log in if not already logged in.

**Closed by nanometrenat** 2020-08-04 21:46 UTC
