### ISSUE TITLE
3W: Multi-region activities

### ISSUE THREAD

**Issue by lauripynnonen** [IFRCGo/go-frontend#1145] opened 2020-04-24 09:23 UTC
Currently, activities (or 'projects') are limited to either a single region or country-wide. This might need an update, as activities potentially span across (domestic) regions. This would then affected how regions are displayed on the table and how bulk upload should work, and we'd need to be extra careful with double counting. Still, potentially an important request.

**Comment by LukeCaley** [comment] 2020-05-11 13:38
Assuming this is a duplicate of https://github.com/IFRCGo/go-frontend/issues/1175 so closing for now @lauripynnonen

**Closed by LukeCaley** 2020-05-11 13:38 UTC
Labels: feature
