### ISSUE TITLE
PER Bug: Save Draft issues on Barbados PER forms

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-frontend#831] opened 2019-09-30 07:00 UTC
This issue so far seems only to be reproducible on the Barbados NS PER Forms.

@guipizzini I may need your help to detail out the steps to reproduce here. But my understanding:

 - Only `Save as Draft` button appears, not `Submit Form`.
 - When clicking `Save as Draft`, the screen then goes blank.

Need some help to identify exactly how to reproduce, and it seems like there maybe other related issues. I think the main thing here to figure out is why the behaviour seems to be different for Barbados vs. other national society PER form pages.

@szabozoltan69 let know if you have any ideas :-)

**Comment by szabozoltan69** [comment] 2019-09-30 15:02
I think that the original plan was: to allow saving Drafts for incomplete forms also, but to allow Submit only for the "all-mandatory-field filled-in" case. So in this sense there is nothing curious in "not allowing submit without all-mandatory-field filled-in" situation. I can accept that it is not very convenient due to the lots of fields, but that was the original plan.

An other issue is that (as I remember) there can be only one drafted form at a time. (Which is quite reasonable to minimize administration). So if someone begin to fill in a new form (at first in draft), then the previous one – "oh MG I worked a lot with it and disappeared" is fully acceptable behaviour. You should work with one form at a time.

**Comment by szabozoltan69** [comment] 2019-09-30 15:09
> Sub-component 14A asks for a benchmark status on GO, but it’s not a benchmark, it should be just a title or text.
This is a real bug and I shall look for the root of it.

> - For the question "Have you had a previous PER capacity assessment?", if you chose "No" as the answer, the page still shows the date and type of last capacity assessment questions, and it is not possible to leave them blank.

Yes, the form works like this. It can be changed via frontend change – but to tell the truth, it has no much importance. In a "No previous" one the date is irrelevant, even with the default value. Anyone can close his/her eyes if does not want to see it.

The same is the case with the other non-relevant date issue. Or, if they are mandatory fields, they should be filled in even if it is not very convenient to get the needed information.

**Comment by szabozoltan69** [comment] 2019-09-30 18:43
The "double draft saving" and the 14A unnecessary benchmark bug is solved. (The non-wanted dates stuff is not.)

Unfortunately some other bugs turned out concerning the numbering of the saved data, so I do not close the issue. This "bad numbering" is caused the 2 kind of "number 3 form", there is a "3" end a "3-2", and annoyingly the 3-2 is the "first" and then comes the normal "3".

**Comment by szabozoltan69** [comment] 2019-09-30 18:44
Please test The "double draft saving" and the "14A unnecessary benchmark" bug.

**Comment by szabozoltan69** [comment] 2019-10-01 12:19
(The fill-out of PER form 3 is awkward. Sometimes it resets to nothing the previously set radio buttons...)

**Comment by LukeCaley** [comment] 2019-11-26 10:34
Unable to test (as of 26/11) - require credentials for PER user for Barbados.

**Comment by szabozoltan69** [comment] 2019-11-26 10:41
In which environment do you need it? (For which username?)

**Comment by teklal** [comment] 2020-01-28 16:31
Tested and saving drafts and submitting other PER form besides "Area 3: Operational capacity 2" for 
 Barbados now works.

However, when I try to open form form "Area 3: Operational capacity 2" for any National Society, all I get is a blank page. This will be outlined in a different ticket.

**Comment by batpad** [comment] 2020-03-02 09:30
@teklal I have been unable to reproduce this, working against a local copy of the database.

Things I tested worked:

 - Fill in "Area 3: Operational Capacity 2" form for Barbados
 - Save as Draft
 - Load Draft
 - Save Form
 - View saved Form

All the above steps worked successfully for me. @teklal I'm assigning back to you - if you are still facing issues here, I will probably need a screenshare or so to see how this might be reproduced.

**Comment by teklal** [comment] 2020-03-02 21:11
This is a curious one as I have not been able to reproduce the issue either but the PER team member who tried to submit forms experienced this. I tested this now again and it works for me. After submitting the form, it didn't however immediately appear in the submitted forms but after some page refreshes and after having submitted other forms I noticed it had appeared there.

**Comment by batpad** [comment] 2020-03-03 12:26
@teklal the form not appearing immediately in the submitted forms is slightly concerning - this is something that was an issue that I thought should be fixed. Is it okay for you if I close this issue, and if you are able to reliably reproduce forms not showing up immediately after being submitted, we create a separate issue for that?

**Comment by teklal** [comment] 2020-03-09 12:23
@batpad sounds good, I'll close this issue now and will open a new one if I'll be able to reproduce this in a reliable way

**Closed by teklal** 2020-03-09 12:23 UTC
